### ISSUE TITLE
Vérifier que la fin de vie de TLS-SNI-01@LetsEncrypt n'impacte pas la production de Mes Aides

### ISSUE THREAD

**Issue by guillett** [betagouv/mes-aides-ui#1083]
> 
> 
> Hello,
> 
> Action may be required to prevent your Let's Encrypt certificate renewals
> from breaking.
> 
> If you already received a similar e-mail, this one contains updated
> information.
> 
> Your Let's Encrypt client used ACME TLS-SNI-01 domain validation to issue
> a certificate in the past 60 days. Below is a list of names and IP
> addresses validated (max of one per account):
> 
>  ludwig.incubateur.net (84.39.45.155) on 2019-01-11
> 
> TLS-SNI-01 validation is reaching end-of-life. It will stop working
> temporarily on February 13th, 2019, and permanently on March 13th, 2019.
> Any certificates issued before then will continue to work for 90 days
> after their issuance date.
> 
> You need to update your ACME client to use an alternative validation
> method (HTTP-01, DNS-01 or TLS-ALPN-01) before this date or your
> certificate renewals will break and existing certificates will start to
> expire.
> 
> Our staging environment already has TLS-SNI-01 disabled, so if you'd like
> to test whether your system will work after February 13, you can run
> against staging: https://letsencrypt.org/docs/staging-environment/
> 
> If you're a Certbot user, you can find more information here:
> https://community.letsencrypt.org/t/how-to-stop-using-tls-sni-01-with-certbot/83210
> 
> Our forum has many threads on this topic. Please search to see if your
> question has been answered, then open a new thread if it has not:
> https://community.letsencrypt.org/
> 
> For more information about the TLS-SNI-01 end-of-life please see our API
> announcement:
> https://community.letsencrypt.org/t/february-13-2019-end-of-life-for-all-tls-sni-01-validation-support/74209
> 
> Thank you,
> Let's Encrypt Staff
> 
>

**Comment by alexsegura** [comment]
À priori, pas de problème, on utilise la méthode `HTTP-01`. 

```
$  . /opt/letsencrypt/.venv/bin/activate
$ letsencrypt renew --dry-run

-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/mes-aides.gouv.fr.conf
-------------------------------------------------------------------------------
Cert not due for renewal, but simulating renewal for dry run
Renewing an existing certificate
Performing the following challenges:
http-01 challenge for mes-aides.gouv.fr
http-01 challenge for www.mes-aides.gouv.fr
Waiting for verification...
Cleaning up challenges

-------------------------------------------------------------------------------
new certificate deployed without reload, fullchain is
/etc/letsencrypt/live/mes-aides.gouv.fr/fullchain.pem
-------------------------------------------------------------------------------
** DRY RUN: simulating 'certbot renew' close to cert expiry
**          (The test certificates below have not been saved.)
```

---

C'est peut-être l'occasion de mettre à jour l'utilisation de LetsEncrypt ?

On utilise une vieille version de LetsEncrypt, [0.14](https://github.com/certbot/certbot/blob/master/CHANGELOG.md#0140---2017-05-04). 
Entre temps, LetsEncrypt a été renommé en CertBot.
C'est un peu déroutant, parce qu'on ne trouve pas la commande standard `certbot` sur le serveur. 
LetsEncrypt est installé avec une vieille méthode, dans un VirtualEnv.

**Comment by alexsegura** [comment]
Ça ne suffit pas j'ai l'impression. 

Sur Ubuntu 14.04, ça installera [toujours l'ancien package](https://github.com/voxpupuli/puppet-letsencrypt/blob/4f6011a051b62232a8bf88d5a0b98b2cf597951c/manifests/params.pp).

Il faudra ajouter les dépôts `jessie-backports` et forcer la méthode d'installation.

**Comment by guillett** [comment]
Merci pour ces infos. Je ferme vu que l'avertissement LetsEncrypt ne nous concerne pas. Pour le changement de version de CertBot, cela ne me parait pas prioritaire. On changera de version au changement de version de l'OS.
