### ISSUE TITLE
Ajouter le CAAH à la liste des droits calculés

### ISSUE THREAD

**Issue by guillett** [betagouv/mes-aides-ui#1107]
[Complément à l'allocation adultes handicapés (AAH)](https://www.service-public.fr/particuliers/vosdroits/F12911) est calculé par le simulateur, pris en compte dans le calcul de certaines prestations mais pas affiché sur la page de résultats ce qui peut créer des confusions.

**Comment by alexsegura** [comment]
Fixé dans #1110
