### ISSUE TITLE
Diviser le fichier droits.js

### ISSUE THREAD

**Issue by monbocal** [betagouv/mes-aides-ui#1118]
Actuellement, droits.js est LE fichier le plus important de Mes Aides (ou du moins, l'un des plus importants).

Il s'agit d'un seul fichier qui vient de dépasser les 800 lignes de code.

Sa maintenance commence à être un peu compliquée.

Je propose qu'on réfléchisse à le séparer en plusieurs fichiers, peut-être en séparant les organismes. C'est pas encore la zone noire, mais on n'est plus en zone blanche.

Merci de votre attention.

**Comment by alexsegura** [comment]
Effectivement, on pourrait par exemple gérer ça dans des fichiers YAML, avec des dossiers / sous-dossiers, un fichier YAML par aide. 

Par commodité, il faudrait que le fichier `droits.js` conserve sa structure, mais qu'il soit généré automatiquement à partir de ces YAML.
