### ISSUE TITLE
Envoyer la date de début de chômage à OpenFisca

### ISSUE THREAD

**Issue by alexsegura** [betagouv/mes-aides-ui#1126]
Une fois que openfisca/openfisca-france#1269 est mergée, il faudra envoyer `date_debut_chomage` (égale à la date du dernier contrat de travail)

**Comment by guillett** [comment]
Je suis en train de faire une montée de version OpenFisca.

Nos tests Ludwig font le job.

http://localhost:9000/tests/559d204131741cd84c323303/show
http://localhost:9000/tests/54d396fd4ec19fce4422725e/show
sont en erreur en montant de version sans modification de notre code.

**Comment by guillett** [comment]
Pour info:

Mois | 'individus.0.specificSituations': 'chomeur' | 'individus.0.chomage_net’ : { $exists : true }
-- | -- | --
2018-01 | 44414 | 17500
2018-02 | 37248 | 14410
2018-03 | 41225 | 15929
2018-04 | 42973 | 16779
2018-05 | 42456 | 16641
2018-06 | 41064 | 15938
2018-07 | 38726 | 14309
2018-08 | 39856 | 14597
2018-09 | 49957 | 17988
2018-10 | 51510 | 19052
2018-11 | 53779 | 20016
2018-12 | 54927 | 20145
2019-01 | 70673 | 27894
2019-02 | 53111 | 20505
2019-03 | 31480 | 12103
