### ISSUE TITLE
Watai ne fonctionne plus

### ISSUE THREAD

**Issue by alexsegura** [betagouv/mes-aides-ui#1128]
Ce matin, la dépendance `saucelabs` est passée en version `2.0`.

~Or, dans le [package.json](https://github.com/MattiSG/Watai/blob/679619ed98a86ba52024960aa7816ba1cfe60e66/package.json#L90) de Watai, il est indiqué `^1.0.1`.~

L'erreur suivante se produit : 

```
TypeError: SauceLabsTransmitter is not a constructor
```

**Comment by alexsegura** [comment]
J'ai ouvert une Issue sur le dépôt de Watai, mais j'ai peu d'espoir qu'elle soit résolue ☹️
Watai n'est plus maintenu. Il est peut-être temps de passer à autre chose ?

MattiSG/Watai#207

**Comment by alexsegura** [comment]
Sinon, on doit pouvoir utiliser Selenium en standalone ([avec Docker](https://github.com/elgalu/docker-selenium)) au lieu de SauceLabs

**Comment by guillett** [comment]
Ça vaut le coup d'essayer de lancer Selenium en local, carrément.

**Comment by alexsegura** [comment]
Je suis dessus 🙂

**Comment by alexsegura** [comment]
Ha pardon, je me suis trompé sur l'analyse du problème.
C'est nous qui installons SauceLabs. Il devrait suffire de forcer la version. 

https://github.com/betagouv/mes-aides-ui/blob/0ccdf342a168d566247f4461b4b06519c97c354a/.circleci/config.yml#L75-L77
