### ISSUE TITLE
Aide Seine-Maritime ACRI

### ISSUE THREAD

**Issue by charlottelecuit** [betagouv/mes-aides-ui#1130]
_Je crée des issues pour toutes les aides pour lesquelles on a déjà un élément (règlement, etc.), ça nous permet d'avoir une meilleure visibilité là-dessus et de prioriser._

- Aide aux collégiens pour la restauration et l'internat
- Règlementation associée :
[délib ACRI 20.06.16.pdf](https://github.com/betagouv/mes-aides-ui/files/2956024/delib.ACRI.20.06.16.pdf)
[1671-2 bourse college.pdf](https://github.com/betagouv/mes-aides-ui/files/2956029/1671-2.bourse.college.pdf)
[Barème ACRI 18-19 (1).docx](https://github.com/betagouv/mes-aides-ui/files/2956031/Bareme.ACRI.18-19.1.docx)

**Comment by guillett** [comment]
Aide ajoutée dans https://github.com/betagouv/mes-aides-ui/wiki/Aides-locales-identifi%C3%A9es
