### ISSUE TITLE
Aide Somme FAJED

### ISSUE THREAD

**Issue by charlottelecuit** [betagouv/mes-aides-ui#1131]
- Fond d'aide aux jeunes en difficulté

- Règlement support : 
[fajed.pdf](https://github.com/betagouv/mes-aides-ui/files/2956047/fajed.pdf)

**Comment by guillett** [comment]
Aide ajoutée dans https://github.com/betagouv/mes-aides-ui/wiki/Aides-locales-identifi%C3%A9es
