### ISSUE TITLE
Aide Côte d'Armor AFI

### ISSUE THREAD

**Issue by charlottelecuit** [betagouv/mes-aides-ui#1133]
- aides aux familles de la CAF 22 : aides départementales de la CAF complémentaires aux aides nationales, décidées par le Conseil d'Administration de la CAF du département
- règlement associé : 
[Règlementation AFI 2019.pdf](https://github.com/betagouv/mes-aides-ui/files/2956066/Reglementation.AFI.2019.pdf)

**Comment by guillett** [comment]
Aide ajoutée dans https://github.com/betagouv/mes-aides-ui/wiki/Aides-locales-identifi%C3%A9es

**Comment by guillett** [comment]
Aide ajoutée dans https://github.com/betagouv/mes-aides-ui/wiki/Aides-locales-identifi%C3%A9es
