### ISSUE TITLE
Proposer l'option d'imprimer le formulaire

### ISSUE THREAD

**Issue by monbocal** [betagouv/mes-aides-ui#1154]
Les travailleurs sociaux nous ont remonté le besoin d'avoir des formulaires papiers proposés en fin de simulation, en parallèle des téléservices.

Cela revient à proposer d'une manière générale, au lieu d'un seul lien de sortie pour chaque aide, plusieurs.

Cela a été soulevé lors de l'OL des Pyrénées Atlantiques et de Seine et Marne.

**Comment by guillett** [comment]
Ça a été fait pour la CMU-C et l'ACS. Tu vois d'autres prestations ?

**Comment by monbocal** [comment]
Je ne sais pas, j'ai juste remonté sans réfléchir pour l'instant.

**Comment by guillett** [comment]
Merci @monbocal !

Comme indiqué dans mon commentaire précédent c'est déjà en ligne. si le besoin ré-émerge pour des aides en particulier on pourra ouvrir une nouvelle issue.

Je ferme.
