### ISSUE TITLE
Revenu fiscal de référence (RFR) et union libre

### ISSUE THREAD

**Issue by monbocal** [betagouv/mes-aides-ui#1155]
Dans le cas d'un couple en union libre, nous ne précisons pas que le RFR à indiquer est le total de celui des deux partenaires.

Cela pourrait également se rapprocher de #126 afin d'éviter de faire le calcul : dans ce cas, en cas d'union libre, permettre à chacun des déclarants d'indiquer son RFR.

Problème soulevé à l'OL de Seine et Marne.

**Comment by guillett** [comment]
Même remarque que sur #1269 

> Dans la nouvelle version, le RFR n'est plus demandé mais calculé dans OpenFisca.
Ce calcul pourrait être à l'origine d'écart dans les cas de situations complexes (en particulier en présence d'abattement fiscal).
Si cela se révèle être un problème, le RFR sera demandé à nouveau.
Pour le moment, je ferme.
