### ISSUE TITLE
Mieux indiquer les cases à cocher en tant qu'apprenti

### ISSUE THREAD

**Issue by monbocal** [betagouv/mes-aides-ui#1156]
Les apprentis ne savent pas forcément où renseigner leurs revenus.

Actuellement, il faut cocher la case "Etudiant", puis indiquer les revenus dans "Salaires hors primes".

Pour un apprenti, ce n'est pas évident : "je suis apprenti, j'ai des revenus d'apprentissage, est ce que je dois les mettre en stages ou en formation continue ?"

Remonté à l'OL de Seine et Marne.

Cette issue peut être mise en relation avec l'issue #505, elle-même en lien avec la PR #730.

**Comment by alexsegura** [comment]
Fixé dans 1822b9654c6a5e4461a1268817e30d7942fbb974
