### ISSUE TITLE
Pertinence de l'aide au logement social

### ISSUE THREAD

**Issue by monbocal** [betagouv/mes-aides-ui#1157]
Le logement social tel que défini sur Mes Aides est assez naïf : si les conditions sont remplies, alors on l'affiche.

Mais dans certains cas, sa pertinence est discutable, notamment par exemple si c'est la seule aide proposée ou bien si l'utilisateur est propriétaire.

L'idée serait de réfléchir à sa pertinence sur la page des résultats au milieu de toutes les autres aides : peut-être faudrait-il la mettre à part afin de ne pas la confondre, avec d'autres aides possiblement dans la même situation ?

Discussion soulevée à l'OL de Seine et Marne.

**Comment by guillett** [comment]
Merci @monbocal ! Résolu pour les propriétaires par #1457. Je ferme.
