### ISSUE TITLE
Ressources des 12 derniers mois : incompréhensions

### ISSUE THREAD

**Issue by monbocal** [betagouv/mes-aides-ui#1158]
Lors de la saisie des ressources, la case "Montants des 12 derniers mois" a demandé un temps de compréhension pour savoir comment la remplir, notamment pour savoir s'il fallait inclure les trois mois précédents ou pas.

Ce problème a été soulevé à l'OpenLab de Seine et Marne.

Historiquement, ce n'est pas la première fois que cette case pose des problèmes à l'utilisateur. Nous avons déjà itéré plusieurs fois sans encore trouver la formule miracle. Peut-être que cette fois, ce sera la bonne.

**Comment by alexsegura** [comment]
Quelles étaient les versions précédentes ? 

D'un point de vue UX, je pense que ce serait plus simple et compréhensible de demander **d'abord** les ressources sur les 12 derniers mois, **puis** les ressources des 3 derniers mois. 

Est-ce qu'on a déjà essayé cette version ?

**Comment by alexsegura** [comment]
Pendant l'OpenLab, j'ai eu une utilisatrice qui a bloqué sur cette erreur. 
La personne dont elle voulait décrire la situation travaillait justement seulement depuis les 3 derniers mois, et dans ce cas cas de figure, il n'est pas évident de comprendre qu'il faut renseigner 3000€ dans la case "Total de avril 2018 à mars 2019 inclus". 

<img width="857" alt="Capture d’écran 2019-04-01 à 16 19 39" src="https://user-images.githubusercontent.com/1162230/55335106-ca76f080-549a-11e9-9e50-e5c138edfeeb.png">

**Comment by monbocal** [comment]
De mémoire, on a essayé de mettre cette case avant, après et "sur les 9 mois précédents" au lieu des 12. Ca n'a jamais vraiment marché aucune des solutions :/

**Comment by alexsegura** [comment]
Sur https://www.mesdroitssociaux.gouv.fr c'est comme ça, donc sensiblement pareil. 

<img width="665" alt="Capture d’écran 2019-04-02 à 09 08 07" src="https://user-images.githubusercontent.com/1162230/55382789-e3c57e80-5526-11e9-9d0b-11d062c2d105.png">

**Comment by guillett** [comment]
Dans la nouvelle version, pour les ressources sur les 12 derniers mois sont demandées soit
- un seul montant est demandé
- 13 montants sont demandées pour le mois courant et les 12 mois précédents.

Il n'y a plus de sommes sur 3 / 9 ou 12 mois à faire.
Je ferme.
