### ISSUE TITLE
Mieux comprendre les résultats pour les corriger sur le simulateur

### ISSUE THREAD

**Issue by monbocal** [betagouv/mes-aides-ui#1162]
Plusieurs travailleurs sociaux m'ont alerté lors de l'openlab. Lorsque certains résultats étaient surprenants, ils avaient besoin de conseils pour vérifier et éventuellement corriger la simulation.

L'amélioration consisterait à trouver un système pour permettre à l'utilisateur d'éventuellement s'auto-corriger pour affiner ses résultats ou bien pour se rassurer d'avoir tout bien fait.

Remonté à l'OpenLab de Seine et Marne.

**Comment by guillett** [comment]
#1198 dans ce cas :)
Merci @monbocal !

**Comment by guillett** [comment]
Dans la version Angular, une modale avait été mise en place pour la PPA.
Dans la nouvelle version Vue (#1438), ne page dédiée permet d'afficher des informations pour chaque prestation.
La logique actuelle aide à la résolution des écarts pour
- la PPA (propriétaire et hébergé comme en Angular).
- les aides qui reposent sur les ressources fiscales

La logique peut être étendue à souhait. Je ferme cet issue générique.

Merci beaucoup @monbocal !
