### ISSUE TITLE
Réduction de loyer de solidarité (RLS) : l'afficher ou non ?

### ISSUE THREAD

**Issue by monbocal** [betagouv/mes-aides-ui#1163]
Les travailleurs sociaux nous ont alerté sur la RLS : https://www.anil.org/aj-reduction-loyer-solidarite-rls-apl/ .

A priori, Open Fisca le calcule, mais nous ne l'affichons pas sur Mes Aides.

A voir comment nous pourrions le faire, afin de donner cette information sans que l'utilisateur final ne soit embrouillé : cette aide ne lui est pas versée.

Remonté dans l'Open Lab de Seine et Marne.

**Comment by guillett** [comment]
Trop techno et impact trop petit. Je ferme.
