### ISSUE TITLE
Préciser sur la page des Ressources à quoi correspondent les ressources

### ISSUE THREAD

**Issue by monbocal** [betagouv/mes-aides-ui#1165]
Sur la page de sélection des ressources, les utilisateurs sont perdus face à toutes les catégories et ont du mal à les sélectionner. Exemple : la différence entre "indemnité" et "pension". On pourrait ajouter dans les barres de chaque rubrique des exemple, comme "Retraite" par exemple.

Problème soulevé lors de l'OpenLab des Pyrénées Atlantiques.

**Comment by alexsegura** [comment]
Idem que #1174
