### ISSUE TITLE
Petit bug sur tooltip UE/Hors UE etc

### ISSUE THREAD

**Issue by charlottelecuit** [betagouv/mes-aides-ui#1171]
@alexsegura tu avais mis ça dans la liste des retours, donc je te le mets ici :)

**Comment by guillett** [comment]
@charlottelecuit peux-tu expliciter le sujet ?

**Comment by alexsegura** [comment]
Le tooltip reste ouvert, des gens bloquaient. 

![tooltip](https://user-images.githubusercontent.com/1162230/54707616-ce714d00-4b41-11e9-982c-9b689a603d67.gif)
