### ISSUE TITLE
Aider à l'auto résolution des problèmes sur la PPA

### ISSUE THREAD

**Issue by guillett** [betagouv/mes-aides-ui#1192]
Il y a des problèmes récurrents sur la PPA (cf. https://github.com/betagouv/mes-aides-ui/pull/1037).

Ça serait bien, pour la PPA, d'avoir un lien en fin de simulation
> Je n'ai pas le montant auquel je m'attendais
qui afficherait une popup avec des remarques générales mais surtout des remarques contextualisées à la situation sous-jacente.

En remarques générales, je pense au
- caractère trimestriel de la PPA, et
- [l'erreur sur les revenus du patrimoine dans le simulateur CAF](https://github.com/betagouv/mes-aides-ui/pull/1037/files#diff-92f2cb2dbb642331f086a7784e42bc10R23)

Pour le particulier, c'est dans #1037.

**Comment by alexsegura** [comment]
Du coup est-ce que ça serait pas bien de merger #1037 déjà ? 🤔

**Comment by guillett** [comment]
Pour moi, #1037 était une étape intermédiaire pour nous, en fin de simulation nous avons beaucoup d'informations pour n'afficher que les informations pertinentes pour la personne derrière son écran. Je trouve, qu'une page de FAQ c'est dommage.
