### ISSUE TITLE
Questions sur l'A/B testing

### ISSUE THREAD

**Issue by alexsegura** [betagouv/mes-aides-ui#1196]
Je me suis penché sur l'A/B testing par rapport à #1195, et j'ai quelques questions sur l'implémentation. Je ne connais pas bien les Custom Variables, donc je peux dire des bêtises. 

- Pourquoi utiliser `localStorage`, alors qu'on utilise un scope de type `visit` ? 
Le `localStorage` est persistent, donc ça ne mettra pas l'utilisateur dans un nouveau segment à chaque visite, si je comprends bien l'implémentation. 
> If you set a custom variable to a visitor, when he comes back one hour or two days later, it will be a new visit and his/her custom variables will be empty.

- Pourquoi utiliser `deleteCustomVariable` ? Ça sert à supprimer la variable pour la visite, donc je ne comprends pas trop pourquoi on fait ça. 

- Si je comprends bien, on incrémente l'index (le slot) à chaque nouvelle variable ? À priori, il n'y a que 5 slots disponible, et on est à 3. 

- Est-ce que ça ne serait pas plus simple d'avoir une seule custom variable, du genre `segment`, qui vaut `A` ou `B` ? Cette variable serait définie une seule fois par visite, quand l'app Angular est démarrée (dans `app.js`)

--- 

Aussi, j'ai l'impression qu'il y a une variable qui a été écrasée, non ? 

<img width="1209" alt="Capture d’écran 2019-04-09 à 16 50 32" src="https://user-images.githubusercontent.com/1162230/55817985-e95a3000-5af5-11e9-81ff-ceaaf8a40949.png">

**Comment by guillett** [comment]
Quelques questions devraient trouver des éléments de réponse dans #1197.

1. Conserver le segment entre visite pour un même utilisateur est, seulement, une _feature_ et pas un bug. C'est pour limiter le niveau de surprise (qui a toujours un coût). C'est pour ça que `localStorage` est utilisé.
2. `deleteCustomVariable` permet de ne pas polluer les stats Matomo une fois les périodes d'A/B testing.
3. On utilise les 5 slots et on les recyclera.
4. En utilisant qu'une seule variable on lie les différents changements entre eux et on ne peut pas vraiment évaluer leur impact.
5. Pour l'AB testing du date picker, j'avais commencé avec deux segments A et B puis je me suis dit que A et B pouvait être explicités donc j'ai changé les noms des segments.


Y-a-t-il des choses encore floues ?

Merci pour tes question !
