### ISSUE TITLE
Éclater les conditions de résidence et de régularité

### ISSUE THREAD

**Issue by MattiSG** [betagouv/mes-aides-ui#122]
En tant que bénéficiaire potentiel ne résidant pas toute l’année en France,
Je peux déterminer mon éligibilité aux prestations en prenant en compte leur conditions de résidence et de régularité de séjour,
Pour évaluer mon éligibilité automatiquement

---

Évaluer notamment les différences selon origine UE / hors UE et débloquer l’accès hors séjour régulier.

**Comment by MattiSG** [comment]
Cela peut impacter #81.

**Comment by Anne-LaureM** [comment]
La situation des étrangers est prise en compte de façon différente d'une prestation à l'autre. 

La condition de résidence stable 
•	RSA : 9 mois 
•	PF : 6 mois 
•	CMUC/ACS : 3 mois 
•	ASPA : 6 mois par 1 an
•	AL : 8 mois par an

La condition de séjour en France 
•	RSA : être titulaire d’un titre de séjour de 3 mois pour les ressortissants de l'UE et de 5 ans pour les ressortissants étrangers hors UE
•	CMUC/ACS : être titulaire d’un titre de séjour ou avoir entamé des démarches pour obtenir un titre de séjour
•	ASPA : être titulaire d’un titre de séjour depuis au moins 10 ans (pour les hors UE)
•	AL : être titulaire d’un titre de séjour 
•	PF : être titulaire d’un titre de séjour

ASS : Il n'y a pas de condition de résidence ou de durée de séjour à prendre en compte (vérifier en amont lors de l’inscription à PE)

**Comment by MattiSG** [comment]
- Tous les ressortissants UE/EEE/Suisse sont éligibles. Le titre de séjour n’a [pas de sens](http://vosdroits.service-public.fr/particuliers/F12017.xhtml) pour [ces populations](http://vosdroits.service-public.fr/particuliers/F2651.xhtml).
- Seul point discriminant : hors de cet espace, la durée d’obtention du titre de séjour fait varier l'éligibilité RSA et ASPA.
- On ignore la condition de trois mois de _résidence_ en France pour le RSA car elle est redondante avec la condition de 9 mois / an de résidence stable.

- [ ] Déterminer les conditions pour l’ASI.
- [ ] Déterminer une appellation ou représentation claire de l’espace EEE+Suisse.
- [ ] Remplacer « nationalité : FR / UE+EEE+CH / autre » par « EEE+Suisse / autre avec titre de séjour valide ».
- [ ] Si autre, poser la question « depuis au moins 5 ans ? » si moins de 65 ans pour l’éligibilité RSA, et « depuis au moins 10 ans ? » si plus de 62 ans (65 ans pour l’ASPA, a priori 62 ans pour l’ASI, à vérifier).

**Comment by MattiSG** [comment]
Pour les conditions de résidence stable, pas de question à poser : il s’agit d’un engagement pour la continuité de l’attribution de l’aide.

- [ ] Vérifier que toutes sont bien présentes sous la forme de conditions textuelles.

On pourra par la suite envisager une représentation graphique unifiée de cette condition dans la page de résultats.

**Comment by fpagnoux** [comment]
En fait, faire varier la question sur la durée de détention d'une carte de séjour en fonction de l'âge peut poser problème. Si j'ai 65 ans mais que je suis en France depuis 6 ans, je peux avoir du RSA vu que l'ASPA me sera refusé. 
Je suis donc plutôt partant par un radio à 3 choix.

**Comment by MattiSG** [comment]
Je verrais plutôt deux questions :

- Depuis plus de 10 ans ?
- Si non : Depuis plus de 5 ans ?

**Comment by fpagnoux** [comment]
ASI : Il faut également un titre de séjour de plus de 10 ans, sauf si réfugié, apatride, ou ancien combattant pour la France.
Source : https://www.service-public.fr/particuliers/vosdroits/F16940
C'est une aide qui n'a pas de condition d'âge minimal,

**Comment by fpagnoux** [comment]
![image](https://cloud.githubusercontent.com/assets/11834997/10104653/189ae6ca-63ab-11e5-859b-48ecc7404ec8.png)

**Comment by fpagnoux** [comment]
PR ouvertes. Deux remarques :
- J'ai réactivé la capture de la nationalité du conjoint. Elle a une importance, car si le conjoint respecte les conditions de durée du titre de séjour, cela peut ouvrir le droit à des prestations.
- En ne faisant plus la différence entre européen et français, on casse quelques features de la génération de CERFA, car les pièces justificatives peuvent être un peu différentes dans ces deux cas. Concrètement, le risque est qu'on demande à un français **trop** de pièces justificatives car on le considère  comme un européen. Cela me paraît pas une conséquence dramatique, mais vous en pensez quoi ?

**Comment by MattiSG** [comment]
@Anne-LaureM Peux-tu regarder si les conditions de résidence changent pour un Européen _inactif_ ?

**Comment by MattiSG** [comment]
> on casse quelques features de la génération de CERFA

Gérait-on réellement la différence aujourd'hui ?

> vous en pensez quoi ?

Que la gestion des démarches est une fonctionnalité qui n'est pas au même niveau de fiabilité que le reste des éléments, et qu'il n'est donc pas bloquant de la dégrader aujourd'hui. Il faut en revanche s'assurer qu'on ne va pas mal remplir un CERFA : soit on le fait correctement, soit on ne le fait pas.

**Comment by Anne-LaureM** [comment]
Le wiki est renseigné avec l'ensemble des éléments.
Il faut ajouter les conditions textuelles pour la Paje, ASF, CF et ASI.

**Comment by MattiSG** [comment]
DU relancé.

**Comment by MattiSG** [comment]
- [ ] Intégrer analyse Droits d’Urgence dans le wiki — @HelaG

**Comment by HelaG** [comment]
Le cas du ressortissant européen inactif inéligible au RSA n'est pas pris en compte cf [test](https://mes-aides.gouv.fr/tests/564ca8e88a5ce0ae423ad21e/show).

**Comment by HelaG** [comment]
Première proposition d’implémentation : un européen dont les ressources sont nulles + en France depuis moins de 5 ans n'a pas de droit à prestations nationales.

**Comment by fpagnoux** [comment]
+1 mail de B.G du 30/12/2016 à 12:03

**Comment by MattiSG** [comment]
Import depuis #439 :

+ 1 Mail du 19 janvier 2017 à 19:25:56.
+1 Mail du 21/02/17 10:26

**Comment by guillett** [comment]
@alexsegura je me dis que ça vaut sûrement le coup de faire ça dans la continuité de la PR #1247. Je vais regarder coté OpenFisca.
