### ISSUE TITLE
Prendre en compte les apprentissages de l'AB testing en cours

### ISSUE THREAD

**Issue by guillett** [betagouv/mes-aides-ui#1242]
- [x] noSpecificSituationCheckbox
    - [x] Analyse, garder la version avec la case " Je ne suis dans aucune de ces situations " car le taux de sortie y est légèrement plus faible.
    - [x] Implémentation
- [x] resourceHelp
    - [x] Analyse
    - [x] Implémentation
- [x] datepicker
    - [x] Analyse
    - [x] Implémentation

https://abtestguide.com/calc/

**Comment by guillett** [comment]
Données
- [sans la checkbox](https://stats.data.gouv.fr/index.php?module=CoreHome&action=index&idSite=9&period=day&date=yesterday#?idSite=9&period=year&date=2019-06-16&category=General_Actions&subcategory=General_Pages&segment=customVariableName4%3D%3DnoSpecificSituationCheckbox;customVariableValue4%3D%3DHide)
- [avec la checkbox](https://stats.data.gouv.fr/index.php?module=CoreHome&action=index&idSite=9&period=day&date=yesterday#?idSite=9&period=year&date=2019-06-15&category=General_Actions&subcategory=General_Pages&segment=customVariableName4%3D%3DnoSpecificSituationCheckbox;customVariableValue4%3D%3DShow)

**Comment by guillett** [comment]
Scenario | URL de la page | Vues | Vues uniques | Taux de rebond | Temps moyen sur la page | Taux de sortie | Temps moyen de génération
-- | -- | -- | -- | -- | -- | -- | --
Sans | /demandeur | 336 225 | 259 376 | 19 % | 00:00:43 | 15 % | 0,19s
Avec | /demandeur | 336 675 | 258 907 | 20 % | 00:00:43 | 14 % | 0,19s

**Comment by ManonLger** [comment]
###resourceHelp
*Données Matomo*

Custom Variable value | Visits | Simulation terminée conversions | Simulation terminée conversion rate
-- | -- | -- | --
Hide | 255,652 | 145,208 | 56.8%
Show | 254,554 | 143,261 | 56.28%

*Résultats A/B-Test Calculator*
```
Significant test result!
Variation B's observed conversion rate (56.28%) was 0.92% lower than variation A's conversion rate (56.80%).You can be 95% confident that this result is a consequence of the changes you made and not a result of random chance.
```

**Comment by ManonLger** [comment]
## datepicker

### Données Matomo
*avec le custom segment "Mobile Safari (Good)"*

Custom Variable value | Visits | Simulation terminée conversions | Simulation terminée conversion rate
-- | -- | -- | --
Hide | 66,298 | 37,379 | 56.38%
Show | 66,003 | 36,920 | 55.94%

### Résultats A/B-Test Calculator
```
The test result is not significant.
The observed difference in conversion rate (-0.79%) isn't big enough to declare a significant winner. There is no real difference in performance between A and B or you need to collect more data.
```
