### ISSUE TITLE
Relancer / Demander un retour aux collectivités locales contactées

### ISSUE THREAD

**Issue by guillett** [betagouv/mes-aides-ui#1243]
Savoir pourquoi ça n'a rien donné pour améliorer notre proposition

**Comment by charlottelecuit** [comment]
- Région Bretagne
- Département Hauts de Seine
- Département de la Somme
- Département Côtes d'Armor

**Comment by charlottelecuit** [comment]
Parmi les contacts de deuxième niveau, on peut aussi ajouter : 
- Pyrénées Atlantiques,
- Seine Maritime,
- Métropole de Lyon,
- Saône et Loire,
- Seine et Marne,
- Haute Garonne,
- Gironde,
- Seine Saint Denis

**Comment by guillett** [comment]
On a plus la capacité de faire du biz dev. Je ferme...
