### ISSUE TITLE
Faire un article de blog pour l'ajout de CCAS

### ISSUE THREAD

**Issue by guillett** [betagouv/mes-aides-ui#1245]
_Pour élargir le public (CT, asso nationales, fondation) cible :_ finalement plus prio
On remplace par l'article CCAS

**Comment by charlottelecuit** [comment]
Lien vers l'article 
https://docs.google.com/document/d/1-SSTHezDqRKP46iYkJHv8NLQEBWV_gVLd2t6a-YxEAs/edit
@alexsegura @ManonLger si vous voulez y jeter un coup d'oeil

**Comment by guillett** [comment]
:clap: @charlottelecuit
