### ISSUE TITLE
Intégrer la capture du RFR dans la capture n-2

### ISSUE THREAD

**Issue by MattiSG** [betagouv/mes-aides-ui#126]
En tant que bénéficiaire potentiel de bourses de collège,
Je peux déclarer mon RFR n-2 dans l’écran de capture de ressources n-2,
Pour n’interagir qu’avec un seul écran

**Comment by MattiSG** [comment]
À traiter avec #125.

**Comment by MattiSG** [comment]
+1 UDAF 92

**Comment by MattiSG** [comment]
Suggestion UDAF 92 : le RFR est-il autre chose que le revenu moins tous les frais et autres déjà capturés ? Si non, pourquoi ne pas le calculer ?

**Comment by guillett** [comment]
Dans la nouvelle version, le RFR n'est plus demandé mais calculé dans OpenFisca.
Ce calcul pourrait être à l'origine d'écart dans les cas de situations complexes (en particulier en présence d'abattement fiscal).
Si cela se révèle être un problème, le RFR sera demandé à nouveau.
Pour le moment, je ferme.
