### ISSUE TITLE
Choix de la nationalité bug

### ISSUE THREAD

**Issue by lucasverra** [betagouv/mes-aides-ui#1282]
See gif 

Je choisie EEE, le resumé annonce sélecteur de nationalité Française 

cf => http://recordit.co/pfJFx5GAwp

**Comment by guillett** [comment]
Merci @lucasverra ! Nous avons récemment mis en place de l'AB testing pour faciliter la saisie de la nationalité et nous avons raté quelque chose. Une version corrigée est en train d'être mise en production.
