### ISSUE TITLE
Envoyer un récapitulatif par email

### ISSUE THREAD

**Issue by guillett** [betagouv/mes-aides-ui#1286]
Suite à de nombreux échanges, je propose l'approche suivante

- V0 Fake it - Une version à coût minimal qui teste _la demande usager_
    - [x] Ajouter un encart à droite permettant la saisie d'un email
    - [x] Ajouter un modèle _followup_ dans MongoDB genre (id, createdAt, simulationId, email) avec un email en clair pour le moment
    - [x] Ne pas envoyer d'email pour le moment :)
    - [x] Modifier les CGU pour indiquer que les emails des personnes qui demandent un recap sont conservés 2 mois (sauf demande contraire)
- V1 - Si y a de la traction :)
    - [x] Ajouter un state au followup
    - [x] Envoyer un email au stock

Idées/pensées en vrac à confronter aux apprentissages qu'on aura fait et si ça a de la traction :
    - éviter de stocker l'email (juste un hash de l'email devrait fonctionner)
    - distinguer l'envoi d'un recap du suivi à 5 jours et 1 mois

WDYT @alexsegura @ManonLger @jeremiecook

**Comment by jeremiecook** [comment]
Hello !

J'aime bien l'idée de tester la traction avant de se lancer dans de grands développement, mais l'idée de l'email est de pouvoir recevoir son récapitulatif directement. C'est plutôt déceptif si on n'envoie rien, non ?

Pour le stockage de l'email, avec un hash, c'est toujours possible de renvoyer une communication 10 jours ou un mois plus tard ?

**Comment by guillett** [comment]
On peux supprimer le bouton si plus de XXX personnes par jour s'inscrivent le temps de coder l'envoi d'email :)

C'est une façon de tester une hypothèse.

Pour le stockage de l'email, je pensais au hash pour les personnes qui ne souhaient que recevoir un email de recap et pas de communication plus tard. (Le hash leur permet d'accéder à nouveau à leur situation sur Mes Aides de façon un peu sécurisée [id/mdp -> identifiant de la simulation / email ])

**Comment by alexsegura** [comment]
Résolu dans #1314

**Comment by guillett** [comment]
Le script suivant a été utilisé en production

```
// Loads
require('../../../backend');
var mongoose = require('mongoose');
// var Situation = mongoose.model('Situation');
var Followup = mongoose.model('Followup');
var followups = require('../../controllers/followups');

Followup.find({email: {$exists: true}}).populate('situation').limit(10).sort({createdAt: 1})
.then(all => {
  return Promise.all(all.map(v => {
    console.log(v._id)
    //console.log(v.situation)
    //console.log(v.situation && v.situation._id)
    //return 'ok';
    return followups.sendEmail(v)
      .catch(v => {
        console.log('error', v);
      })
    }));
}).finally(() => {
  process.exit();
});
```
