### ISSUE TITLE
Encodage HTML dans les emails

### ISSUE THREAD

**Issue by alexsegura** [betagouv/mes-aides-ui#1316]
La description peut contenir du HTML, peut-être utiliser [mjml-raw](https://mjml.io/documentation/#mjml-raw) ? 

<img width="618" alt="Capture d’écran 2019-08-06 à 18 47 37" src="https://user-images.githubusercontent.com/1162230/62559521-741c2300-b87b-11e9-8c13-52afd13bb610.png">

**Comment by guillett** [comment]
Ou mettre un & dans le template mustache.

Le 6 août 2019 18:53:26 GMT+02:00, Alexandre Segura <notifications@github.com> a écrit :
>La description peut contenir du HTML, peut-être utiliser
>[mjml-raw](https://mjml.io/documentation/#mjml-raw) ? >
>>
><img width="618" alt="Capture d’écran 2019-08-06 à 18 47 37"
>src="https://user-images.githubusercontent.com/1162230/62559521-741c2300-b87b-11e9-8c13-52afd13bb610.png">>
>>
>>
>-- >
>You are receiving this because you are subscribed to this thread.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/betagouv/mes-aides-ui/issues/1316

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.
