### ISSUE TITLE
Champs de date sur la page "vous"/"demandeur", branche vue

### ISSUE THREAD

**Issue by SebastienTouze** [betagouv/mes-aides-ui#1382]
Sur cette page 2 champs de date sont présents mais l'interface est non homogène entre la date de naissance et le champ "date de fin de contrat" (3 `input type=number` vs `input` simple). 
Il serait plus beau d'utiliser des `input type="date"` ou `input type="month"`.

**Comment by guillett** [comment]
Comme discuté lors du sprint Open Source, les `input type="date"` ou `input type="month"` sont pratiques pour des dates récentes ou actuelle (RDV, concert dans le futur proche) mais pas très pratique pour une date dans le passé. J'ai associé cette issue à la PR que tu as ouverte sur le sujet #1397.
