### ISSUE TITLE
Page de résultats blanche  sur la branche vue

### ISSUE THREAD

**Issue by SebastienTouze** [betagouv/mes-aides-ui#1384]
Sur la page résultat, après avoir ajouté des revenus 2017 (pour une simulation en 2019) et après validation de ceux-ci J'arrive sur une page "vide" : seule le titre de la page, le header et le footer sont présents. 
![Capture du 2019-11-20 17-00-40](https://user-images.githubusercontent.com/5538298/69254987-56b75e80-0bb7-11ea-9b27-e0638096299d.png)

**Comment by guillett** [comment]
Merci beaucoup @SebastienTouze !!! 
Des PRs mergées dans la journée dont #1381 devraient avoir corrigées le problème. Si il persiste, pourrais-tu nous envoyer le lien en haut de https://www.whatsmybrowser.org/ (pour en savoir plus sur ton navigateur).

Utilises-tu un ad-blocker ?

**Comment by SebastienTouze** [comment]
Hello
Effectivement je n'ai plus de page blanche et une belle page me proposant des aides ! 
Je clos. Bravo au passage pour l'intégration de vuex =)
