### ISSUE TITLE
Préciser à un bénéficiaire potentiel du RSA Socle son éligibilité automatique à la CMU-C

### ISSUE THREAD

**Issue by HelaG** [betagouv/mes-aides-ui#143]
En tant qu'utilisateur qui obtient le RSA Socle et la CMU-C en résultat de sa simulation,

Je peux savoir comment est calculé mon droit à la CMU-C,

Pour faire valoir mes droits

**Comment by HelaG** [comment]
En cas d’éligibilité au RSA Socle, le bénéficiaire peut automatiquement demander la CMU-C. 

Le droit lui sera provisoirement ouvert (à compter de la date de dépôt de son dossier de demande de RSA) le temps de l'instruction de la demande de RSA, avant d'être prolongé pour 9mois (si le droit au RSA est effectivement ouvert).

cf. [test](https://mes-aides.gouv.fr/acceptance-tests/546b473c492eaff5637e3c92/show)

**Comment by guillett** [comment]
Le test est vert, les personnes éligibles au RSA le sont aussi à la CMU-C. Je ferme.
