### ISSUE TITLE
Fournir automatiquement les dossiers de demande complémentaire pour le RSA

### ISSUE THREAD

**Issue by louisremi** [betagouv/mes-aides-ui#157]
Un dossier de demande de RSA peut requérir d'être accompagné de dossiers de demandes complémentaires en fonction de la situation du demandeur. Voici ceux que je connais : 
- demande complémentaire pour les jeunes de moins de 25 ans (14130*02)
- demande complémentaire pour les travailleurs non-salariés (13882*03)
- demande complémentaires pour les auto-entrepreneurs ?? (on m'en a parlé à la CAF de Lyon, mais j'ai pas l'impression que ce soit un cerfa, ça doit être spécifique au Rhône)

Il serait utile que Mes Aides les propose quand ils sont requis, et éventuellement les pré-remplisse.

**Comment by MattiSG** [comment]
Génial, merci beaucoup pour cette proposition !

L'amélioration de l'accompagnement à l'engagement des démarches est aujourd'hui un peu lointain, mais voilà une belle base pour traiter le sujet pour le RSA quand nous y viendrons  :)

Cette issue sera bien entendu mise à jour quand nous aborderons le sujet.

**Comment by guillett** [comment]
Merci @louisremi pour cette proposition. À la fin de l'année dernière les demandes sont faites en ligne ou bien en CAF directement (pour le meilleur et pour le pire).

Les personnes éligibles sont redirigées vers le téléservice.
Je ferme donc cet issue.
