### ISSUE TITLE
Forcer à zéro une ressource que le bénéficiaire potentiel déclare ne plus percevoir au mois courant

### ISSUE THREAD

**Issue by fpagnoux** [betagouv/mes-aides-ui#188]
En tant que bénéficiaire potentiel qui déclare une ressource interrompue au mois M,
La valeur de cette ressource est forcée à zéro dans Openfisca pour ce mois

**Comment by MattiSG** [comment]
@fpagnoux Toujours d'actualité ?

**Comment by fpagnoux** [comment]
Je ne sais plus d'où venait le besoin exactement, mais en effet on ne le fait pas.
Ça ne peut concerner qu'une personne qui déclare cesser de percevoir une prestation que l'on calcule par ailleurs.

**Comment by MattiSG** [comment]
Je le comprends comme le fait que la case à cocher pour indiquer qu'on ne perçoit plus une ressource ne sert absolument à rien pour le moment 🤔

**Comment by fpagnoux** [comment]
Supposons que je déclare toucher un salaire les 3 derniers mois, on va me demander si je pense un toucher un ce mois-ci.
- Si je réponds oui, on va prendre mon salaire M-1 et le copier-coller sur M.
- Si je réponds non, on ne fait rien.
Pour un salaire, ça s'arrête là.
Disons maintenant que je déclare toucher des AF sur les 3 derniers mois, et que je déclare que je n'en toucherais plus au mois M. On ne fait rien, donc on n'envoie aucune valeur pour les AF au mois M. Et donc Openfisca va les recalculer.

**Comment by guillett** [comment]
Dans la nouvelle version, la valeur pour le mois courant est explicitement demandée.
La logique de copier-coller n'est plus implémentée.
