### ISSUE TITLE
Ne pas afficher de RSA pour un ressortissant européen inactif

### ISSUE THREAD

**Issue by HelaG** [betagouv/mes-aides-ui#206]
Non éligibilité au RSA d'un européen inactif entré en France à la recherche d'un emploi [cf test](https://mes-aides.gouv.fr/tests/564ca8e88a5ce0ae423ad21e/show)

Connected to #122

**Comment by ManonLger** [comment]
Résolu par https://github.com/openfisca/openfisca-france/pull/1371 (bientôt :grin:)
