### ISSUE TITLE
Gérer les logements de fonction

### ISSUE THREAD

**Issue by fpagnoux** [betagouv/mes-aides-ui#214]
En tant que bénéficiaire potentiel bénéficiant d'un logement de fonction,
Je peux déclarer ma situation, 
Pour connaître mes droits.

---

Cette situation semble être celle d'un occupant à titre gratuit, qui a été reformulée en "Hebergé" avec comme sous-texte "chez un particulier".

**Comment by MattiSG** [comment]
« Y compris chez particulier » ?
« Fonction ou particulier » ?

**Comment by monbocal** [comment]
Up :
"je suis entrain de remplir un questionnaire pour évaluer nos droits à 15 aides nationales.
pour ce qui est du logement, je ne rentre dans aucun des 4 cas proposés étant logé par nécessité absolue de service."
https://location-immobilier.ooreka.fr/astuce/voir/571969/logement-par-necessite-absolue-de-service

**Comment by guillett** [comment]
Au vu des précédents commentaires, on devrait pouvoir s'en sortir avec une reformulation. @monbocal aurais-tu une idée de formulation plus claire et plus inclusive  du sous-titre de la case « Hébergé » ?

**Comment by monbocal** [comment]
Est ce que "Hebergé", c'est "Vous habitez chez quelqu'un" ou bien "Vous êtes locataire avec un loyer de 0 euros ?" . Les personnes en logement de fonction ou NAS payent par exemple leurs charges locatives. Bref, c'est compliqué dans ma tête. On aurait un expert sous la main ?

**Comment by guillett** [comment]
Je te laisse retrouver si tu peux des cas de tests :
+ Locataire sans loyer
+ Nécessité Absolue de Service
+ Situation en EHPAD

**Comment by monbocal** [comment]
NAS : Mail du 20/09/2017 21:58 (pas de simulation)
EPHAD : 26/10/2017 14:21 ; 10/03/2017 16:23
Locataire sans loyer : plus difficile à retrouver, j'ai le cas d'une SCI familiale au 28/07/2017 9:00

**Comment by monbocal** [comment]
EPHAD : situation en foyer, déjà précisé dans la page locataire.

Reste des cas à entrer pour les deux autres dans Ludwig

**Comment by monbocal** [comment]
Et revoir la page logement

**Comment by monbocal** [comment]
Up

**Comment by guillett** [comment]
@monbocal merci !
