### ISSUE TITLE
Calculer le montant de l'AAH

### ISSUE THREAD

**Issue by HelaG** [betagouv/mes-aides-ui#216]
En tant que bénéficiaire potentiel de l'AAH je peux calculer le montant de l'aide

Connected to #172

**Comment by HelaG** [comment]
- [ ] Déployer la version calculable de l'AAH sur Next
- [ ] Copier les tests Yaml dans Ludwig
- [ ] Valider les tests par les experts

**Comment by MattiSG** [comment]
En attente de tests de la CAF sur aah.mes-aides.beta.gouv.fr.

**Comment by monbocal** [comment]
J'up ce vieux thread : si on relançait le process ?

**Comment by guillett** [comment]
Pour moi c'est bon.
