### ISSUE TITLE
Prendre en compte l'AEEH dans l'éligibilité à PLF

### ISSUE THREAD

**Issue by HelaG** [betagouv/mes-aides-ui#217]
En tant que parisien avec 1 enfant handicapé à charge, je peux calculer mon éligibilité PLF en tenant compte de l'AEEH de l'enfant. 

http://www.paris.fr/aidesaulogement#aides-au-logement-de-la-ville-de-paris_10

**Comment by MattiSG** [comment]
Connected to #191.
