### ISSUE TITLE
Le tooltip "CA" ne marche pas

### ISSUE THREAD

**Issue by Florent2** [betagouv/mes-aides-ui#219]
sur cette page "CA" semble avoir un tooltip associé mais quand on passe la souris dessus ou on clique, rien ne s'affiche

![img](https://monosnap.com/file/rgmnsu4cAIrpF2hv9r54yQMBhYA61d.png)

testé sur Mac Chrome

**Comment by HelaG** [comment]
Salut Florent, merci de ton feedback! 
Le tooltip devrait s'afficher comme ça :
![ca d un tns](https://cloud.githubusercontent.com/assets/12069445/11538304/bca8035a-9921-11e5-993d-0df6d1d79ac9.png)

Si ce n'est pas le cas, on va chercher l'origine et voir ce qu'on peut faire pour améliorer ça! Malheureusement ça risque d'attendre encore un peu, comme tu peux le voir on a un [joli backlog](https://waffle.io/sgmap/mes-aides-api)!

**Comment by Florent2** [comment]
merci pour ta réponse, je te confirme que je ne vois pas le tooltip

c'est complètement pas urgent :)
