### ISSUE TITLE
Ajouter les chèques énergie

### ISSUE THREAD

**Issue by HelaG** [betagouv/mes-aides-ui#222]
Nouveau dispositif, prévu par l'article 60 du projet de loi sur la transition énergétique, qui remplace la tarification sociale de l'énergie.

Contact partenaire (rencontrée à l'occasion de la conf au PIMMS Antony) : radia.aouichat@edf.fr

**Comment by MattiSG** [comment]
Voir l'excellent site du médiateur de l'énergie pour toutes les [conditions d'éligibilité](http://www.energie-info.fr/Fiches-pratiques/Ma-facture-mon-compteur/Ai-je-droit-aux-tarifs-sociaux) et [conséquences d'impayés](http://www.energie-info.fr/Fiches-pratiques/Reclamations-et-litiges/J-ai-des-difficultes-de-paiement).

**Comment by monbocal** [comment]
Ouverture de la PR en 2015. Réponse de Matti en 2016.

Moi, Sylvain, suis fier de vous annoncer qu'en 2018, l'aide est intégrée via la PR https://github.com/betagouv/mes-aides-ui/pull/803 .
