### ISSUE TITLE
Clarifier l'articulation des ressources trimestrielles et annuelles

### ISSUE THREAD

**Issue by HelaG** [betagouv/mes-aides-ui#224]
En tant qu'utilisateurs de Mes Aides,

Je peux remplir mes ressources trimestrielles OU annuelles 

Et avoir une évaluation de mes ressources cohérente sans avoir à faire de calcul mental

Cf. mail du Erreur du 09/12 + Retour utilisateur PIMMS Antony + Mail du 10/12 de Y.G.

**Comment by monbocal** [comment]
Rendu obsolète avec l'option de déclarer un mois uniquement sur la page ressources.
