### ISSUE TITLE
Obtenir un récapitulatif de ses droits en fin de simulation

### ISSUE THREAD

**Issue by HelaG** [betagouv/mes-aides-ui#265]
En tant que bénéficiaire éligible à des prestations
Je peux télécharger un récapitulatif de mes droits en fin de simulation
Pour garder sous la main la liste des démarches à engager
- [ ] Mail usager  Apr 12, 2016 at 8:57

**Comment by monbocal** [comment]
+1 mail 17/02/17 15:42

**Comment by monbocal** [comment]
+1 mail 09/03/17 12:03

**Comment by casvp** [comment]
@guillett 

Effectivement, je rebondis sur cette demande exprimée par les usagers. 

L'introduction d'une fonction d'impression en fin de simulation serait utile aux agents qui utilisent le simulateur comme outil de travail. Ils pourraient ainsi remettre un document à l'usager en fin de simulation. Au CASVP quand un agent oriente un usager vers un partenaire il est d'usage de lui remettre une fiche avec l'adresse et les horaires du partenaire. La fiche permet à l'usager de garder une trace écrite des échanges qu'il a eus avec l'agent. 

On peut imaginer un bouton "imprimez le résultat de votre simulation" qui correspondrait à une capture d'écran de la liste des aides proposées.

**Comment by guillett** [comment]
En fait c'est fait. Je ferme.
