### ISSUE TITLE
Tracer les accès aux formulaires

### ISSUE THREAD

**Issue by MattiSG** [betagouv/mes-aides-ui#335]
Jusqu'ici, l'outil de suivi analytique (Piwik) traçait une partie des accès aux formulaires, par le biais des pages de présentation Cerfa.
Avec #333, les liens sont directs et pour la grande majorité externe. Il conviendrait donc d'enregistrer des événements (et probablement de notifier aussi l'étude d'impact https://mes-droits.fr).

**Comment by MattiSG** [comment]
Également, ajouter des paramètres `utm_source` et `utm_campaign` à tous les liens sortants.

**Comment by MattiSG** [comment]
Les liens sortants auraient déjà du être suivis avec la configuration `enableLinkTracking` de Piwik…

**Comment by guillett** [comment]
Les clics sur les liens d'informations et les liens d'action (formulaire, téléservice, instructions) sont enregistrés [dans Piwik via des actions](https://stats.data.gouv.fr/index.php?module=CoreHome&action=index&idSite=9&period=day&date=today#?module=Events&action=index&idSite=9&period=day&date=today). L'ajout de `utm_source` ne fait pas parti des sujets à traiter prochainement.

Je ferme cette issue.
