### ISSUE TITLE
Ajouter l'APA

### ISSUE THREAD

**Issue by MattiSG** [betagouv/mes-aides-ui#395]
- Mail du 31/10/2016 à 23:09.

**Comment by MattiSG** [comment]
+1 mail du 19 déc. 2016 à 10:59

**Comment by MattiSG** [comment]
En cours d'implémentation dans OpenFisca par @elsaperdrix dans https://github.com/openfisca/openfisca-france/issues/638. Une fois cela fait, il nous suffira de vérifier que les éléments à capturer le sont déjà dans l'interface et, le cas échéant, à ajouter les captures correspondantes.

@elsaperdrix Êtes-vous déjà en lien avec l'organisme liquidateur de la prestation, ou implémentez-vous ces règles uniquement sur la base du droit ?

**Comment by elsaperdrix** [comment]
L'APA est simulée  uniquement sur la base du droit pour le moment.

**Comment by MattiSG** [comment]
@elsaperdrix Ok, mais avec ajout de tests, c'est bien ça ?

**Comment by monbocal** [comment]
L'APA à domicile a été ajouté dans le simulateur.
