### ISSUE TITLE
Inclure toutes les ressources imposables dans l'estimation du n-2

### ISSUE THREAD

**Issue by MattiSG** [betagouv/mes-aides-ui#430]
> Les pensions d'invalidité déclarées sur la page ressource ne sont pas intégrés dans l'estimation des revenus N-2. 

Source : test utilisateur du 02/01/2017.

**Comment by MattiSG** [comment]
Également, s'assurer que la suppression d'une ressources la supprime bien de l'estimation du N-2.

**Comment by monbocal** [comment]
+1, mail du 13/04/2017 à 19:07 : le montant affiché "Cette valeur vaut X pour [année]" ne prend que les rentes en compte et cela peut induire en erreur les utilisateurs

**Comment by guillett** [comment]
@fpagnoux a fait remarquer que l'on pourrait récupérer l'estimation auprès d'OpenFisca qui fera un meilleur boulot que nous. Je trouve que c'est mieux que ma suggestion/PR https://github.com/sgmap/mes-aides-ui/pull/543.

**Comment by guillett** [comment]
Résolution partielle via https://github.com/sgmap/mes-aides-ui/pull/543.

**Comment by MattiSG** [comment]
Que manque-t-il pour que la résolution soit complète ?

**Comment by guillett** [comment]
En fait, je crois que [la résolution est complète](https://github.com/betagouv/mes-aides-ui/blob/master/app/js/constants/ressources.js#L339).

Si un besoin similaire on ouvrira un nouvel issue. Je ferme celui ci.
