### ISSUE TITLE
Intégrer le calcul d'éligibilité au logement social

### ISSUE THREAD

**Issue by fpagnoux** [betagouv/mes-aides-ui#431]
- Mail du 7 janvier 2017 à 16:37

**Comment by MattiSG** [comment]
- https://www.legifrance.gouv.fr/affichTexte.do;jsessionid=186AC8F0B7590C42DAA390BA6C89612B.tpdila11v_1?cidTexte=JORFTEXT000033681769&dateTexte=&oldAction=rechJO&categorieLien=id&idJO=JORFCONT000033680662
- https://www.anil.org/documentation-experte/analyses-juridiques-jurisprudence/analyses-juridiques/2009/logement-hlm-plafonds-de-ressources/
- http://www.hlm.coop/IMG/pdf/Memento_Locatif_2017.pdf

**Comment by MattiSG** [comment]
Extraction et reformulation du mail du 10 janvier 2017 à 22:05:55 :

> Les plafonds de ressources sont mis à jour chaque année pour chacun des types de logements sociaux.
>
> Les logements  construits ou améliorés avec des prêts de l’Etat sont attribués sous certaines conditions de ressources. Les différents modes de financement, anciens et nouveaux, (PLA, PLAI, PLUS, PLS, PLI...) génèrent différents plafonds de ressources.
>
> C'est le revenu  fiscal de référence qui est pris en compte pour savoir si on est en dessous d'un plafond, le revenu fisscal de référence correspond aux ressources imposables (à l'exclusion des aides sociales délivrées par la CAF par exemple). [Référence](https://www.service-public.fr/particuliers/vosdroits/F3153).
>
> - PLAI : logements très sociaux
> - PLUS : logements sociaux
> - PLS : logements sociaux 
> - PLI : logements intermédiaires
>
> Les plafonds évoluent donc en fonction :
> - du type de logement social
> - de la composition du foyer ( en gros le nombre d'occupants du foyer
> - de la localisation du logement
>
> Pour l’application des plafonds de ressources, il faut distinguer en Ile-de-France deux zones :
>
> - Paris et les communes limitrophes (zone 1 bis)
> - le reste de la région (zone 1).
>
> La seule exception à ce découpage est le plafond de ressources PLI, qui considère toute l’Ile-de-France comme une seule zone.
>
> Pour vous situer dans le tableau des plafonds de ressources, vous devez d’abord déterminer votre catégorie de ménage :
>
> - une personne seule,
> - deux personnes n’ayant aucune personne à charge, à l’exclusion des jeunes ménages(1), 
> - trois personnes ou une personne seule avec une personne à charge ou jeunes ménages(1) sans personne à charge,
> - quatre personnes ou une personne seule avec deux personnes à charge, 
> - cinq personnes ou une personne seule avec trois personnes à charge, 
> - six personnes ou une personne seule avec quatre personnes à charge.
>
> Ensuite, en fonction de vos revenus fiscaux de référence de l’année n-2, vous pouvez déterminer le ou les plafonds de ressources des logements qui seront susceptibles de vous être proposés. Si vous entrez dans un de ces 7 plafonds, vous êtes éligible à un logement social.
>
> Plafonds de ressources 2017 (applicables sur le revenu imposable 2015), fixés par circulaire du Ministère du Logement :
>
> ![plafond_2017](https://cloud.githubusercontent.com/assets/222463/21856749/6375f9d0-d823-11e6-8338-2d5499e12bd7.JPG)
>
> Les bailleurs sociaux prennent en compte _toutes_ les ressources, y compris les aides sociales, lors de l'évaluation du taux d'effort (`(loyer mensuel + charges) / ressources mensuelles`). Le taux d'effort doit habituellement être ≤ 0,33.
> 
> ## Exemples de simulateurs
>
> - http://www.opievoy.fr/logement/Mes-demarches/Puis-je-beneficier-d-un-logement-social en banlieue parisienne (données de plafonds obsolètes).
> - http://www.groupe-sai.fr/ai-je-droit-au-logement-social (plafonds non documentés, mais correspond probablement aux plafonds PLS région 2015).

**Comment by MattiSG** [comment]
Contacts de bailleurs sociaux potentiellement partenaires obtenus.

**Comment by MattiSG** [comment]
Contact pris avec la sous-direction des politiques de l'habitat à la DHUP.

**Comment by alexsegura** [comment]
Est-ce qu'on renverrait pas les gens directement sur [demande-logement-social.gouv.fr](https://www.demande-logement-social.gouv.fr/) ?

Et sur les sites des départements selon le cas (voir sur le site ci-dessus)
