### ISSUE TITLE
Arrondir à l'euro inférieur

### ISSUE THREAD

**Issue by MattiSG** [betagouv/mes-aides-ui#434]
Actuellement, les montants sont arrondis à la dizaine d'euro la plus proche.

Le niveau de fiabilité actuel devrait permettre de généraliser l'arrondi à l'euro.

- [ ] Obtenir une lecture par prestation des résultats des tests.
- [ ] Déterminer la fiabilité relative de chaque prestation.
- [ ] Arrondir à l'euro inférieur les plus fiables.

**Comment by guillett** [comment]
Je pense qu'on est prêt pour cet issue.

C'est une opportunité de faire du nettoyage
- [`roundToNearest10`)(https://github.com/betagouv/mes-aides-ui/blob/master/app/js/constants/droits.js#L268)
- [`roundToNearestCent`](https://github.com/betagouv/mes-aides-ui/blob/master/app/js/constants/droits.js#L715)

Ces deux attributs peuvent être remplacés par un unique attribut qui indique le niveau auquel il faut faire un arrondi.

@alexsegura que penses de la proposition suivante en 2 étapes
- [ ] Refactoring en gardant l'arrondi de 10 par défaut (PR)
- [ ] Changer le niveau des prestations pour lesquelles on peut passer à l'euro près.

**Comment by alexsegura** [comment]
Je ne suis pas certain que c'est la bonne méthode, mais voici ce que j'ai fait pour tenter d'identifier les aides sur lesquelles ont peut réduire la précision. 

1/ J'ai fait un script qui créé un CSV à partir des résultats de tests Ludwig. 
J'ai pris uniquement en compte les tests qui ne sont pas en échec. 
Il créé un CSV avec les colonnes suivantes : 

|Aide         |Différence|
|-------------|----------|
|aide_logement|-2        |
|rsa          |5         |
|aspa         |0         |
|…            |…         |

2/ J'ai ouvert ce CSV dans LibreOffice, et j'ai créé une [table de pivot](https://help.libreoffice.org/Calc/Creating_Pivot_Tables) à partir de ces données. 
Ça permet d'obtenir des stats groupées (minimum, maximum, moyenne et écart type)

Avec les résultats dont la différence est de zéro (test exact)

<img width="896" alt="capture d ecran 2019-02-12 a 16 16 22" src="https://user-images.githubusercontent.com/1162230/52647030-3948bc00-2ee4-11e9-8d07-b60025b9d8b6.png">

Sans les résultats dont la différence est de zéro

<img width="764" alt="capture d ecran 2019-02-12 a 16 52 31" src="https://user-images.githubusercontent.com/1162230/52648343-a4938d80-2ee6-11e9-8d0d-3b839f675f15.png">

**Comment by guillett** [comment]
Avec #1117 et #1115 comme disait @alexsegura on peut dire que cette issue est résolue.

7 prestations sont encore à la dizaine près et la PPA est à 5 euros. près.
