### ISSUE TITLE
Détecter les incidents en production

### ISSUE THREAD

**Issue by fpagnoux** [betagouv/mes-aides-ui#436]
En tant que développeur mes-aides,
Je peux rapidement savoir quand une simulation produit une erreur,
Pour pouvoir détecter et réparer rapidement les bugs.

**Comment by fpagnoux** [comment]
Aujourd'hui, si un utilisateur rencontre une erreur lors de sa simulation (en particulier, requête rejetée par Openfisca), nous ne pouvons que très difficilement nous en rendre compte.
Les logs sont difficilement accessibles, et les analyser à la main n'est pas réaliste.

Le fait que des utilisateurs nous écrivent à `bug@mes-aides.gouv.fr` semble indiquer que ces erreurs arrivent de temps en temps.

**Comment by fpagnoux** [comment]
Solutions possibles que je vois: 
- Analyser les logs proprement, par exemple avec Kibana. Discuté avec @Ismael-Hery, semble intéressant et offrir d'autres usages, mais nécessite un investissement conséquent. Peut-être est-ce quelque chose dont on peut parler au nouveau dev.
- Utiliser une solution comme Sentry (voir peut être avec les équipes MPS qui l'utilisent), qui gère l'alerting. Mais sans doute aussi un investissement.
- Se baser sur piwik et angulartics (#411). 

@MattiSG, la 3eme solution me semble être potentiellement la moins couteuse, comment est-ce qu'on pourrait l'implémenter ? On peut déclencher manuellement un évènement via angulartics et faire le suivi via piwik ? Est-ce qu'on peut ajouter un objet JSON à un évènement ?

**Comment by MattiSG** [comment]
Déclencher un événement est très simple suite à #411, cf la doc de http://angulartics.github.io. On peut ajouter de la donnée arbitraire à l'événement, mais je doute qu'il n'y ait pas de limite de taille, et l'interface de Piwik n'est dans tous les cas pas faite pour consulter de la donnée.
Un point important dans cet arbitrage est probablement la réponse à la question : que voudrait-on enregistrer précisément ?

L'analyse des logs est sans aucun doutes intéressante, mais parle-t-on des logs d'OpenFisca ou de Mes Aides ? Cela me semble effectivement un investissement nécessaire pour OpenFisca dans les mois qui viennent. Pour Mes Aides, vu que tout se passe sur le client, je suis moins convaincu. Il existe des solutions de suivi d'erreur côté client.

Plus largement, il me semblerait utile de préciser cette issue : quand on parle de simulation qui génère une erreur, parle-t-on spécifiquement d'une erreur OpenFisca ou de tout type d'erreur ?

**Comment by jdesboeufs** [comment]
Pour information l'instance [sentry.data.gouv.fr](http://sentry.data.gouv.fr) est accessible aux startups.
Même si j'aime beaucoup Kibana, dans votre cas Sentry est clairement le quick-win.

**Comment by MattiSG** [comment]
@fpagnoux est-ce que #442 et #443 ont résolu le problème pour toi ?

**Comment by alexsegura** [comment]
Sentry FTW

**Comment by alexsegura** [comment]
@guillett proposition en attendant de voir si on peut mettre ça sur une instance Sentry auto-hébergée : utiliser [sentry.io](https://sentry.io/) avec un compte gratuit. Ça permet de voir si ça apporte un plus avec un coût minimal.
