### ISSUE TITLE
Ne pas appliquer la règle du 80/40 pour les revenus autres que le salaire

### ISSUE THREAD

**Issue by fpagnoux** [betagouv/mes-aides-ui#445]
L'abattement [80/40](http://www.kevinpolisano.com/?p=742) ne s'applique qu'aux revenus salariés en milieu ordinaire.

Il ne faut donc pas l'appliquer sur les pensions, comme dans [ce test](http://aah.mes-aides.beta.gouv.fr/tests/582b0d0167831ca264e93e3a/show).

- [ ] Quid des revenus non salariés ?

**Comment by guillett** [comment]
Fait dans https://github.com/openfisca/openfisca-france/pull/1157/commits/564ca005412aad3fd4d127d78d5a19d7458ad28f.

Je ferme cette issue.
