### ISSUE TITLE
Modifier le focus vers le CTA sur la homepage

### ISSUE THREAD

**Issue by Flightan** [betagouv/mes-aides-ui#477]
Quand on arrive sur la page et que l'on commence à naviguer vers le bas, le focus se remet sur le CTA.
![not_cool](https://cloud.githubusercontent.com/assets/1475946/23407452/3f42b5d2-fdc4-11e6-93ba-7aa736d93935.gif)

**Comment by MattiSG** [comment]
Ah, oui. Est-ce un bug ou une feature ? 😛 
Merci pour le rapport.

**Comment by Flightan** [comment]
Plus je tombe dessus, plus je suis convaincu que c'est un bug...

**Comment by monbocal** [comment]
Corrigé !
