### ISSUE TITLE
Ajouter un navigateur incompatible (Safari 5)

### ISSUE THREAD

**Issue by monbocal** [betagouv/mes-aides-ui#486]
En tant que bénéficiaire potentiel,
Je souhaite qu'on m'informe que Safari 5 n'est pas supporté,
Afin que je passe sur Chrome par exemple

--

Cf Mail du 09/03/17 14:52 & suivants : problème technique sur Safari 5

**Comment by monbocal** [comment]
D'une manière générale, tous les iPad sous iOS 5 (dernière version stable de la 1re génération ; la G2 permet iOS 9) semblent impactés par ce bug.

**Comment by MattiSG** [comment]
+1 mail du 11 mars 2017 à 11:16.

**Comment by monbocal** [comment]
+1 mail 11/03/17 16:01

**Comment by alexsegura** [comment]
Je pense qu'on peut fermer cette issue. 
En regardant les emails listés plus haut, l'erreur est `'undefined' is not an object`, et je ne pense pas que ça ait un rapport avec Safari 5, mais plutôt avec #1030. 

<img width="480" alt="capture d ecran 2019-02-06 a 11 07 07" src="https://user-images.githubusercontent.com/1162230/52334267-8cf86880-29ff-11e9-87c2-49206e71f26c.png">

De plus, on constate une baisse radicale des visites avec Safari 5, il n'y en a pratiquement plus. 
Je ne m'explique pas trop cette baisse, peut-être que Apple l'a supprimé ou a forcé les mises à jour ? 

<img width="1057" alt="capture d ecran 2019-02-06 a 11 05 21" src="https://user-images.githubusercontent.com/1162230/52334385-d47ef480-29ff-11e9-8f5b-5d8b20171244.png">
