### ISSUE TITLE
Préciser la nationalité des autres individus du ménage

### ISSUE THREAD

**Issue by monbocal** [betagouv/mes-aides-ui#497]
Mise à jour mars 2019 :
La nationalité du conjoint et des enfants intervient dans de nombreux calculs pratiques. Lors de l'OL en Seine et Marne, le RSA a notamment été présenté comme impacté.

Deux options ont été alors proposées :
- soit capturer la nationalité des conjoints / enfants et proposer un meilleur montant
- soit préciser dans les conditions supplémentaires d'attributions des aides que le montant dépend également de la nationalité du conjoint / enfants

La seconde option pourrait être proposée en rustine en attendant la première.

### Conjoint

En tant que bénéficiaire potentiel,
Je souhaite entrer la nationalité de mon partenaire / conjoint,
Pour calculer mes aides en fonction de ma situation réelle plutôt qu'en supposant que mon partenaire / conjoint est français.

cf. #461

### Enfants

En tant que bénéficiaire potentiel d'une aide,
Je souhaite préciser la nationalité des enfants dont j'ai la responsabilité
Afin de mieux calculer mes droits

--

Message FB du 13/03/17 :  les enfants sous responsabilité mais non français n'ont pas le droit aux bourses par exemple, d'autres droits pourraient également être impactés.

**Comment by monbocal** [comment]
Up, j'ai eu deux cas en quelques jours à ce sujet

**Comment by guillett** [comment]
Il faut aussi mettre ça en relation aux discussions sur #546

**Comment by monbocal** [comment]
Up :)

**Comment by monbocal** [comment]
J'uppe afin qu'on considère sérieusement une intégration future de #461 , en relation avec #546 et avec une intégration OpenFisca.

**Comment by monbocal** [comment]
Up et mise à jour avec les retours de l'OL de la Seine et Marne.

**Comment by guillett** [comment]
Email le 08/05/2019 à 15:33
Retour OpenLab HdS
