### ISSUE TITLE
Ajouter le statut d'apprenti

### ISSUE THREAD

**Issue by monbocal** [betagouv/mes-aides-ui#505]
En tant que bénéficiaire potentiel d'une aide,
Je souhaite déclarer mon statut d'apprenti et mes revenus associés,
Afin d'avoir une meilleure estimation de mes droits sociaux.

--
Mail du 14/03/17 18:52
> Comment sont pris en compte les salaires des apprentis ?

Mail du 15/03/17 16:57
> Je suis apprenti, j'ai donc déclaré mes revenus dans "salaires", mais il me semble qu'en tant qu'apprenti j'ai un rabattement fiscal de plus de 10.000€/an. Le logiciel de simulation ne semble pas prendre en compte cela, car a aucun moment je n'ai eu à spécifier que j'étais apprenti. (ou alors fallait-il que je déclare mes revenus dans "stage rémunéré" ou "formation professionnelle" ? en tout cas ce n'est pas précisé).

Mail du 16/03/17 11:10
> La prise en compte des statuts particuliers (apprentissage) pourrait être pratique puisque les droits sont spécifiques à ce statut 

Mail du 10/05/19 10:16
> Je recherche un site actualisé sur les aides pour les apprentis et les étudiants.
Le vôtre est intéressant mais il serait judicieux d’indiquer en page d’accueil la qualité d’apprenti afin de faciliter l’accès à l’information et aux démarches en se sentant immédiatement concerné.

Cela a des impacts par exemple sur la PPA : http://www.contratdapprentissage.fr/prime-dactivite-apprentissage.php

**Comment by guillett** [comment]
L'éligibilité de l'apprenti semble être la même que pour l'étudiant.
https://www.legifrance.gouv.fr/affichCode.do?idSectionTA=LEGISCTA000031087625&cidTexte=LEGITEXT000006073189&dateTexte=20160101

Il semblerait qu'OpenFisca contienne déjà le nécessaire :
https://legislation.openfisca.fr/ppa_eligibilite_etudiants

@monbocal penses-tu qu'il faille investiguer davantage sur le sujet ?

**Comment by monbocal** [comment]
Si les calculs sont déjà intégrés sous la catégorie "Etudiant", alors pour éviter des confusions, peut-être faut-il préciser dans le champs à cocher Vous Êtes comme ceci :

 Etudiant.e / Apprenti.e

Afin de lever le doute ?

**Comment by guillett** [comment]
A voir, à rapprocher avec #317

**Comment by MattiSG** [comment]
Si on veut modifier l'intitulé, il faut vérifier qu'un apprenti peut toucher des bourses, et que cela n'a pas d'impact sur d'autres éligibilités (i.e. que d'autres prestations ne soient conditionnées qu'à être étudiant·e et non apprenti·e). Si oui (ou si c'est trop coûteux), on peut ajouter une autre situation particulière (= case à cocher) « Apprenti·e ».

**Comment by monbocal** [comment]
Up. J'ai le cas d'un apprenti, l'allocation logement n'est pas correctement calculée : 59ea0009be59cc58d081e4ca . A voir si ce n'est pas un manque dans OpenFisca pour appliquer des conditions partculières ?

**Comment by monbocal** [comment]
Les seules bourses qu'on calcule sont celles des collégiens, lycéens. Aucun risque de conflit de mêler les deux dans ce cas.
