### ISSUE TITLE
Revaloriser les prestations au 1er avril 2017

### ISSUE THREAD

**Issue by monbocal** [betagouv/mes-aides-ui#528]
À partir du 1er avril 2017, les prestations familiales et sociales (sauf les pensions de retraite) seront revalorisées de 0,3 %, les prestations sociales étant revalorisées une fois par an (en avril) en fonction de l'évolution moyenne de l'indice des prix hors tabac sur les 12 derniers mois.

- plafonds de ressources prévus pour le bénéfice de la CMU complémentaire et de l'aide à l'acquisition d'une complémentaire santé (ACS) ;
- indemnités en capital et rentes d'accident du travail ;
- prime d'activité ;
- RSA (Revenu de solidarité active) ;
- AAH (Allocation adulte handicapé) ;
- ASS (Allocation de solidarité spécifique) ;
- pensions d'invalidité ;
- ASI (Allocation supplémentaire d'invalidité) ;
- Aspa (Allocation de solidarité aux personnes âgées) ;
- Ata (Allocation temporaire d'attente).

Pour les pensions de retraites, la revalorisation devrait intervenir le 1er octobre 2017.

Source : https://www.service-public.fr/particuliers/actualites/A1143

**Comment by guillett** [comment]
Nouveau lien: https://www.service-public.fr/particuliers/actualites/A11437

**Comment by MattiSG** [comment]
- ASF : https://www.service-public.fr/particuliers/actualites/A11602
- CMU-C / ACS : https://www.service-public.fr/particuliers/actualites/A11604

**Comment by monbocal** [comment]
ASPA et ASI : https://github.com/openfisca/openfisca-france/pull/747

**Comment by guillett** [comment]
Liens importants (+ cités par) :

https://www.legifrance.gouv.fr/affichCodeArticle.do?cidTexte=LEGITEXT000006073189&idArticle=LEGIARTI000006743403&dateTexte=&categorieLien=cid

https://www.legifrance.gouv.fr/affichCodeArticle.do?cidTexte=LEGITEXT000006073189&idArticle=LEGIARTI000006741258&dateTexte=&categorieLien=cid

**Comment by MattiSG** [comment]
@guillett cela a-t-il été corrigé par https://github.com/openfisca/openfisca-france/pull/767 ?

**Comment by monbocal** [comment]
Rendu obsolète par la mise à jour 2018
