### ISSUE TITLE
Remplir automatiquement les montants forfaitaires sur la page ressources

### ISSUE THREAD

**Issue by monbocal** [betagouv/mes-aides-ui#606]
Certaines aides ont des montants forfaitaires : soit on la touche et le montant est défini, soit on ne la touche pas. Par exemple, le Complément à l'Allocation Adultes Handicapés est de 179.31 euros ( https://www.service-public.fr/particuliers/vosdroits/F12911 ).

Dans le cas de ces ressources, pourquoi ne pas changer le champs associé en case "J'ai perçu cette aide ce mois-ci / Depuis X / De X à Y / Les mois W, Y, Z" afin que l'utilisateur n'ai pas à taper son montant ?

**Comment by guillett** [comment]
C'est une idée intéressante, quelles sont les autres prestations éligibles à ce pré-remplissage ?
Je pensais à l'AAH et à l'ASF mais toutes deux sont différentielles.

**Comment by guillett** [comment]
@monbocal vois-tu d'autres ressources forfaites que le CAAH ?

**Comment by guillett** [comment]
En lien avec https://github.com/openfisca/openfisca-france/issues/1188

**Comment by monbocal** [comment]
Montant fixe : ASF*, 115,30 - MVA, 104,77 - Retraite du combattant, 748,80 € par an

Montant fixe mais minoré : ASF encore, en cas de parents séparés : 115,30 moins la pension

Autre possibilité d'extension : remplir avec les montants maximums. Ex: AAH à 860 par défaut ? Mais ça peut rajouter des erreurs en masse.

**Comment by ManonLger** [comment]
Après investigation avec @monbocal, visiblement le Complément de ressources a remplacé le CAAH (qui ne reste que de façon transitoire).
https://www.legifrance.gouv.fr/affichCodeArticle.do;jsessionid=6D9841673220B972DCA864BE1DF93490.tplgfr36s_3?idArticle=LEGIARTI000019505277&cidTexte=LEGITEXT000006073189&dateTexte=20181023
Je propose d'en fixer le montant à partir de celui-ci : https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/parameters/prestations/minima_sociaux/caah/montant_complement_ressources.yaml

Les autres montants que je pense fixer :
+ MVA (https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/parameters/prestations/minima_sociaux/caah/majoration_vie_autonome.yaml)
+ Retraite du combattant (@monbocal saurais-tu retrouver où est ce montant dans les paramètres Openfisca ?)
+ C'est tout. :)

Question bonus : comment vous savez que l'AAH n'est pas fixée par exemple, alors qu'ici on a un montant fixe ? https://github.com/openfisca/openfisca-france/tree/master/openfisca_france/parameters/prestations/minima_sociaux/aah/montant.yaml

**Comment by ManonLger** [comment]
J'ai commencé à travailler là-dessus sur cette branche : https://github.com/betagouv/mes-aides-ui/tree/montants-fixes

**Comment by alexsegura** [comment]
On ferme cette Issue ou tu dois encore ajouter d'autres montants forfaitaires @ManonLger  ?

**Comment by ManonLger** [comment]
Non c'est bon, on peut fermer ! :)
