### ISSUE TITLE
Améliorer la description du patrimoine

### ISSUE THREAD

**Issue by monbocal** [betagouv/mes-aides-ui#617]
Sur la page de fin de simulation, les intitulés concernant l'épargne demandent vérification.

Actuellement, on est sur :
- Montant total de votre épargne sur livrets - Livret A, LDD, LEP et Livret Jeune uniquement.
- Montant de votre épargne qui ne génère pas de revenus - Compte courant, assurance-vie, SICAV de capitalisation, FCP, PEL ou PERP.

Cependant, pour la Caf, il y a d'un côté le compte courant (qui n'est pas pris compte) et de l'autre tous les livrets d'épargne (montant total) : 
"On entend par patrimoine financier les montants actuels déposés sur les comptes suivants :
Livret A, Livret jeune, Livret d’épargne populaire (LEP), Livret de développement durable (LDD), Compte d’épargne-logement (CEL), Plan d’épargne logement (PEL) de moins de 12 ans, Plan d’épargne d’entreprise, Plan d’épargne en actions (PEA), Assurance vie (sauf rentes-survie et épargne handicap)."

De plus, il faut préciser que les livrets des enfants sont également pris en compte ainsi que les livrets des conjoints.

Il faudrait vérifier comment ces valeurs sont envoyées à OpenFisca, quelles aides les utilisent, afin de pouvoir les affiner et les améliorer.

**Comment by guillett** [comment]
Ces éléments là semblent uniquement être pris en compte dans le calcul du RSA.

**Comment by monbocal** [comment]
Elles entrent aussi en compte pour l'APL à partir du moment où c'est supérieur à 30K : https://www.service-public.fr/particuliers/vosdroits/F12006

**Comment by guillett** [comment]
Je te laisse faire le recoupement avec le RSA : https://www.service-public.fr/particuliers/vosdroits/F24585

**Comment by monbocal** [comment]
_Je vais prendre des notes sur cette issue avant de faire la synthèse._

Simulateur APL
- On entend par patrimoine mobilier produisant des revenus imposables : 
Les montants de vos différents placements financiers de source française ou étrangère : 
la valeur des actions, parts sociales ou obligations, les bons du trésor, l'assurance vie en cas de retrait avant 8 ans de détention, les comptes à terme, les Sicav et Fonds communs de placement... 

- On entend par patrimoine mobilier produisant des revenus non imposables, les montants déposés sur les comptes suivants : 
Livret A, Livret jeune, Livret d'épargne populaire (LEP), Livret de développement durable (LDD), Plan d'épargne populaire (PEP), Compte d'épargne-logement (CEL), Plan d'épargne logement (PEL), Plan d'épargne d'entreprise, Plan d'épargne en actions (PEA), Assurance vie. 

Les deux sont demandés si présents.

**Comment by monbocal** [comment]
Prime d'activité : ne s'applique pas.

**Comment by monbocal** [comment]
Simulateur RSA demande "Total de l'argent placé : Compte d'épargne (PEL, CEL, Livret A, LEP, LDD...), Assurance Vie".

**Comment by monbocal** [comment]
Sur Service Public :
APL, ALS et ALF (soit toutes les AL) : la valeur de votre patrimoine immobilier et financier ainsi que celui de la personne avec laquelle vous vivez en couple et des personnes vivant habituellement à votre foyer, lorsque cette valeur est supérieure à 30 000 €,

RSA :
les capitaux placés (les biens non productifs de revenu réel sont considérés comme produisant fictivement un revenu annuel égal à 3 % de leur montant ; sont notamment visés les contrats d'assurance-vie qui procurent des revenus à échéance, mais ne sont pas concernés par le taux de 3 % les livrets A qui procurent annuellement des capitaux. Vous devez seulement déclarer les intérêts annuellement perçus. S'agissant des sommes figurant sur les comptes courants, elles ne sont pas retenues dans le calcul du RSA),

**Comment by monbocal** [comment]
**-> Il y a là une incohérence entre service public et le simulateur de la Caf. Service public explicite la différence entre l'assurance vie et le RSA. Le simulateur de la Caf les met dans le même panier.**

**Comment by guillett** [comment]
Pour le RSA : 

>  Pour l'appréciation des ressources des postulants prévue à l'article L. 132-1, les biens non productifs de revenu, à l'exclusion de ceux constituant l'habitation principale du demandeur, sont considérés comme procurant un revenu annuel égal à 50 % de leur valeur locative s'il s'agit d'immeubles bâtis, à 80 % de cette valeur s'il s'agit de terrains non bâtis et à 3 % du montant des capitaux.


https://www.legifrance.gouv.fr/affichCodeArticle.do;jsessionid=39242E277AF42FA18A0AAD6260749BA7.tplgfr38s_1?cidTexte=LEGITEXT000006074069&idArticle=LEGIARTI000006905072&dateTexte=20171106&categorieLien=cid#LEGIARTI000006905072

**Comment by guillett** [comment]
On va commencer sur le patrimoine mobilier puis regarder le patrimoine immobilier.

**Comment by monbocal** [comment]
On a deux solutions pour l'épargne (ie le patrimoine mobilier)

A 3 cases :
(1) Livret A

(2) Epargne non imposable
Livret jeune, Livret d'épargne populaire (LEP), Livret de développement durable (LDD), Plan d'épargne populaire (PEP), Compte d'épargne-logement (CEL), Plan d'épargne logement (PEL), Plan d'épargne d'entreprise, Plan d'épargne en actions (PEA), Assurance vie.

(3) Epargne imposable
Les montants de vos différents placements financiers de source française ou étrangère :
la valeur des actions, parts sociales ou obligations, les bons du trésor, l'assurance vie en cas de retrait avant 8 ans de détention, les comptes à terme, les Sicav et Fonds communs de placement...

Pour le RSA, on prend en compte 1% de (1), 3% de (2) et 3% de (3).
Pour l'allocation logement, on fait le total des sommes (dégressivité à partir de 30000 euros)

A 2 cases :
(1) Epargne non imposable
Livret A, Livret jeune, Livret d'épargne populaire (LEP), Livret de développement durable (LDD), Plan d'épargne populaire (PEP), Compte d'épargne-logement (CEL), Plan d'épargne logement (PEL), Plan d'épargne d'entreprise, Plan d'épargne en actions (PEA), Assurance vie.

(2) Epargne imposable
Les montants de vos différents placements financiers de source française ou étrangère :
la valeur des actions, parts sociales ou obligations, les bons du trésor, l'assurance vie en cas de retrait avant 8 ans de détention, les comptes à terme, les Sicav et Fonds communs de placement...

Pour le RSA, on prend en compte 3% de (1) et 3% de (2).
Pour l'allocation logement, on fait le total des sommes (dégressivité à partir de 30000 euros)

**Comment by guillett** [comment]
Pour l'AL on fait :
Si le patrimoine est > 30.000 alors les ressources sont augmentées de 3% du patrimoine générant des revenus non imposables i.e.

```python
patrimoine = patrimoine_revenus_imposables + patrimoine_revenus_non_imposables
( patrimoine > 30000 ) * 0.03 * patrimoine_revenus_non_imposables
```

**Comment by guillett** [comment]
En attente d'information de la DHUP.

**Comment by guillett** [comment]
> Les livrets générant des revenus non-imposables ou n'ayant pas générés de revenus imposables sont considérés comme générant 3% par an…

**Comment by monbocal** [comment]
Yep. _Dura lex sed lex_.

**Comment by guillett** [comment]
En attente de https://github.com/openfisca/openfisca-france/pull/902

**Comment by guillett** [comment]
## Proposition d'UI du patrimoine
![capture d ecran 2018-03-02 a 16 58 00](https://user-images.githubusercontent.com/1410356/36908223-ec485b64-1e3a-11e8-9cc4-c30428133193.png)

**Comment by guillett** [comment]
## Dans le simulateur AL de caf.fr
![capture d ecran 2018-03-02 a 17 28 39](https://user-images.githubusercontent.com/1410356/36909735-304742fe-1e3f-11e8-953d-df47c6a709a7.png)
