### ISSUE TITLE
Préciser l'arrondi de calcul

### ISSUE THREAD

**Issue by guillett** [betagouv/mes-aides-ui#681]
Un flux important d'email provient de fait que les montants affichés sont arrondis à 10€.

Il faut le préciser pour éviter sur les usagers nous contactent pour ces faux négatifs (ie. écarts dûs aux arrondis).

Ex à retravailler : Les montants données sont à titre indicatif et arrondis à une dizaine d'euros près. 

Problème : les prestas de Paris sont à l'euro juste.

**Comment by monbocal** [comment]
Ce commit pourrait régler cette issue. Je n'en suis pas satisfait, quelque chose me dérange sans savoir quoi : ton avis ?
https://github.com/sgmap/mes-aides-ui/commit/7c8b6234eb419f2fd211d27c38c562a2dee0976f

**Comment by guillett** [comment]
Done by #689
