### ISSUE TITLE
Améliorer l'envoi des mails

### ISSUE THREAD

**Issue by monbocal** [betagouv/mes-aides-ui#698]
Un formulaire pour envoyer les mails de réclamation / suggestion c'est mauvais car on n'est pas certain d'avoir la bonne adresse de réponse + poss. piratage du script.

Mais un formulaire qui permet de préremplir le mail avec des cases à cocher ?

J'ai une suggestion 1/0 -> affichage lien suggestion
Les montants ne sont pas les bons -> entrer nom presta + montant obtenu ou simulé

A réfléchir ?

**Comment by guillett** [comment]
Le travail d'amélioration du support utilisateur a été entamé sur la nouvelle version avec la création d'une page pour gérer les montants inattendus dans #1438.

Je ferme cet issue. Un nouveau pourra être ouvert dans le futur à partir des nouvels apprentissages et des nouvelles propositions.
