### ISSUE TITLE
Forcer la vue ressources sur les trois derniers mois pour les ressources ponctuelles

### ISSUE THREAD

**Issue by monbocal** [betagouv/mes-aides-ui#710]
Certaines ressources de la page ressources :

- Primes (dont 13e mois)
- Indemnités de licenciement 

ont actuellement la vue simplifiée "Entrez le montant mensuel".

Ca entraine des erreurs de saisie pour les utilisateurs et une augmentation de leurs ressources potentielles.

Peut-on forcer la vue 3 derniers mois sur ces ressources ?

**Comment by monbocal** [comment]
En lien un peu avec https://github.com/sgmap/mes-aides-ui/issues/732

**Comment by monbocal** [comment]
Et si pour les ressources ponctuelles, quand on remplissait la case unique, au lieu de propager à toute l'année, on ne propageait qu'au mois précédent ?

**Comment by guillett** [comment]
@monbocal je n'ai pas compris ta dernière remarque.

**Comment by guillett** [comment]
Fixed by #988. Thanks @ManonLger :)
