### ISSUE TITLE
Revenus du conjoint inconnus

### ISSUE THREAD

**Issue by MattiSG** [betagouv/mes-aides-ui#75]
En tant que bénéficiaire potentiel ne connaissant pas les revenus de mon conjoint,
Je peux signaler cette inconnue,
Pour déterminer mon éligibilité sans mettre de montants nuls

**Comment by guillett** [comment]
Il n'y a pas retours usagers qui indique que la saisie obligatoire des ressources de conjoint est rédhibitoire. En cas de méconnaissance, l'usager est libre de faire l'estimation de son choix (nulle, à la baisse, etc.). Pas de consensus particulier, ni suivi récent, je ferme l'issue.
