### ISSUE TITLE
AL primo accédant à réduire / supprimer ?

### ISSUE THREAD

**Issue by monbocal** [betagouv/mes-aides-ui#761]
L'AL pour les primo accédants est supprimée / rabottée en 2018 (en cours d'investigation) :

pour https://www.francetvinfo.fr/economie/immobilier/reforme-du-logement/achat-de-logement-moins-d-aide-pour-les-plus-modestes_2524543.html,
> elles ne seront versées qu'aux personnes modestes qui achètent hors des grandes villes et uniquement du logement ancien.

https://argent.boursier.com/immobilier/actualites/mauvaise-nouvelle-pour-lapl-accession-4697.html
> Le gouvernement a finalement réussi à faire supprimer l’APL accession dans le neuf à partir du 1er janvier 2018, tout en maintenant cette aide pour 2 ans dans l’ancien, mais seulement dans certaines zones détendues. Un arrêté ministériel doit maintenant préciser lesquelles des communes ne se caractérisant pas par un déséquilibre important entre l'offre et la demande de logements entraînant des difficultés d'accès au logement dans le parc résidentiel existant satisfont à ces conditions de zones détendues.

**Comment by monbocal** [comment]
Sur la page de la Caf, l'AL pour les primo accédants est réservée aux personnes qui ont signé un prêt avant le 1er février 2018 : http://www.caf.fr/allocataires/droits-et-prestations/s-informer-sur-les-aides/logement-et-cadre-de-vie/les-aides-au-logement?active=tab1

> accédant à la propriété et remboursant un prêt conventionné signé avant le 1er février 2018 et ce, quelque soit la commune d'implantation;

A voir si ça vaudrait le coup dans le simulateur de rajouter une case "J'ai signé mon prêt avant le 1er février 2018" et à modifier les règles dans OpenFisca France de l'AL primo accédant avec une condition ?

**Comment by guillett** [comment]
Des ressources
https://www.legifrance.gouv.fr/affichCode.do?idSectionTA=LEGISCTA000006159050&cidTexte=LEGITEXT000006074096
et
https://www.legifrance.gouv.fr/affichCodeArticle.do;jsessionid=E2C1B9D67F3C0B09770505BB4B7D5C5D.tplgfr23s_3?cidTexte=LEGITEXT000006074096&idArticle=LEGIARTI000006898798&dateTexte=20190129&categorieLien=cid#LEGIARTI000006898798

**Comment by alexsegura** [comment]
@monbocal sur ce sujet, est-ce que tu as un email ou quoi qui met en avant le problème ? 

La [formule](https://fr.openfisca.org/legislation/aides_logement_primo_accedant_eligibilite) me semble bonne avec ces "nouvelles" dispositions, depuis cette Pull Request openfisca/openfisca-france#1138

**Comment by monbocal** [comment]
Je n'ai pas très bien compris la formule d'OpenFisca, je ne peux pas te répondre, je vais essayer de la regarder plus en détail.

**Comment by monbocal** [comment]
https://www.vousfinancer.com/franchise/presse/communiques/lapl-accession-supprimee-dans-le-neuf-et-limitee-dans-lancien-aux-zones-detendues

**Comment by guillett** [comment]
@monbocal as tu une situation en erreur dans Mes Aides sur ce sujet ?
Sans cela le temps investi risque d'être trop grand pas rapport aux bénéfices.

**Comment by monbocal** [comment]
Oui, j'en ai reçu une encore ce matin : 5c5095b76ca0bb4cfa2ee3fd .

Je ne comprends pas, on n'est pas dans le cas "est ce que ça vaut le temps qu'on va y passer", mais bien d'une aide qui a été en partie supprimée et en partie modifiée depuis un an et qu'on continue d'afficher sans en tenir compte... Actuellement si une personne propriétaire voit apparaitre l'aide au logement c'est de la roulette sur les conditions de demande, on affiche des informations qui ne sont d'actualité que si on est dans le passé.

On peut voir pour tricher de notre côté pour éviter d'ajouter trop de champs sur le simulateur, en modifiant les textes de présentation par exemple, mais dans tous les cas c'est pas du temps qu'on perd, c'est du temps qu'on doit prendre si on veut renseigner nos utilisateurs.

**Comment by guillett** [comment]
:thinking: 

On est toujours dans le cas "est ce que ça vaut le temps qu'on y passe" et faire de la veille et/ou de l'investigation législative n'est pas notre meilleure compétence.

Un cas de test permet d'objectiver le problème et de le quantifier.

Mais surtout, un cas de test permet de trouver un équilibre entre :
- arriver à un point satisfaisant et
- limiter l'investissement en compréhension de la législation française.

**Comment by alexsegura** [comment]
Voici un extrait de la trace pour la situation.
Pour une raison qui m'échappe, on force dans Mes Aides la date du prêt au 31 décembre 2018 (voir le bout de code en-dessous)

Est-ce qu'il ne suffirait pas tout simplement de demander à quelle date a été signé le prêt, comme le suggère @monbocal, et le commentaire dans le code ci-dessous ?

<img width="1008" alt="capture d ecran 2019-01-30 a 12 54 40" src="https://user-images.githubusercontent.com/1162230/51979960-db9d8400-248e-11e9-8a17-4d463abdb76a.png">

https://github.com/betagouv/mes-aides-ui/blob/df043edca6229ce2c24a9f7f4d6af49ceb2bffb2/backend/lib/openfisca/mapping/index.js#L97-L115

**Comment by alexsegura** [comment]
Vu avec @guillett, on affiche effectivement un montant positif pour l'aide au logement dans tous les cas, parce qu'on hardcode `aide_logement_date_pret_conventionne` au 31/12/2017. 

Le top ce serait d'avoir la date exacte de signature du prêt, mais c'est peut-être un peu contraignant. Comme suggéré par @monbocal, on peut l'obtenir de manière plus ou moins détournée. 

> rajouter une case "J'ai signé mon prêt avant le 1er février 2018"

Ou encore plus simple, "j'ai signé mon prêt avant l'année 2018". 

Suggéré par @guillett : faire de l'A/B testing en affichant soit une case à cocher simple, soit un sélecteur de date.
