### ISSUE TITLE
Idée : indiquer les aides non calculées ?

### ISSUE THREAD

**Issue by monbocal** [betagouv/mes-aides-ui#762]
Rapport à 2 mails coup sur coup sur "votre simulateur ne m'a pas indiqué que j'avais droit à la mutuelle, alors je ne sais pas si j'y ai droit". A creuser ?

**Comment by monbocal** [comment]
Possibilité d'intégration : sur la 1re page, proposer en optionnel un choix à cocher "Vous souhaitez surtout avoir des renseignements sur X, Y, Z...." et sur la page des résultats, avoir un cadre en premier "X : OK, Y, KO, Z, KO" ?

**Comment by monbocal** [comment]
Meilleure intégration :
Sur la page des résultats, rajouter un champs de recherche à auto complétion pour "mettre en avant une aide".
Si l'aide est calculée : alors on l'affiche dépliée, avec le montant.
Si l'aide n'est pas calculable : alors on affiche l'aide avec un message "Vous n'êtes a priori pas éligible à cette aide".

Cela évite d'ajouter des informations sur le simulateur ou de demander des informations en cours de simulation ou bien de surcharger volontairement la page des résultats.

**Comment by monbocal** [comment]
Suite à la remarque de thomas, effectivement, la seule fois où on nous pose cette question, c'est par rapport à la CMU-C / ACS. Une manière naïve d'inclure serait un bandeau "Vous n'êtes pas éligible à la CMU-C / ACS", idéalement uniquement si l'utilisateur vient d'un lien de l'assurance maladie ? @guillett wdyt ?

**Comment by alexsegura** [comment]
Voilà à quoi ça ressemblerait pour présenter les aides auxquelles les usagers venant de Ameli.fr n'ont **pas** droit. Des suggestions ?

<img width="875" alt="capture d ecran 2018-09-05 a 15 31 26" src="https://user-images.githubusercontent.com/1162230/45096557-150cd600-b121-11e8-9d47-43d76e24d902.png">
