### ISSUE TITLE
aide pour jouer des profils d'utilisateurs

### ISSUE THREAD

**Issue by julien111** [betagouv/mes-aides-ui#801]
Bonjour,

je voudrais effectuer des tests qui consistent à jouer des profils d'utilisateurs. Par exemple, je crée un profil de manière automatique et en poussant les entrées du profil je souhaite récupérer la liste des aides auquel ce profil à le droit. Savez vous comment je peux m'y prendre car j'ai du mal à trouver le pont d'entrée pour cela (j'ai juste les bases en javascript)?

Merci

Julien

**Comment by guillett** [comment]
Bonjour @julien111, je ne suis pas sûr de comprendre le problème, n'hésitez pas à nous contacter par email sur bonjour@mes-aides.gouv.fr.
