### ISSUE TITLE
Demander si on les connait les revenus n-2 plus tôt ?

### ISSUE THREAD

**Issue by monbocal** [betagouv/mes-aides-ui#808]
Beaucoup de retours sont souvent d'utilisateurs dont les revenus n-2 n'ont pas été renseigné. Ajouter une option au cours de la simulation, skippable, "Je connais mes revenus n-2, je les remplis" ?

**Comment by guillett** [comment]
Les retours problématiques ont été limités en ajoutant une page pour permettre la résolution en autonomie des écarts récurrents #1438 

Merci @monbocal .

Je clos.
