### ISSUE TITLE
Orienter les usagers vers des points d'accueil physique dès la page d'accueil

### ISSUE THREAD

**Issue by guillett** [betagouv/mes-aides-ui#809]
Aujourd'hui, il n'y a qu'un CTA sur la page d'accueil.
Certains usagers préféreraient peut-être se déplacer pour avoir un accompagnement en _présentiel_ dans un point d'accueil.

Un second CTA pourrait être « Être accompagner pour évaluer vos droits » qui redirigerait vers une page demandant le code postal et la ville et qui afficherait une liste (puis une carte) d'établissements comme sur la page de résultats.

Une telle page nous permettrait de connaitre si des usagers ont ce besoin (d'accompagnement en _présentiel_) et cibler les CCAS à contacter en fonction de l'usage de cette nouvelle page.

@monbocal WDYT ?

**Comment by monbocal** [comment]
Comme discuté, je pense qu'il faudrait faire attention à ce que cette fonction n'entre pas en concurrence avec le simulateur. En effet à la base, Mes Aides est un simulateur de prestations sociales à destination des particuliers et de ceux qui les accompagnent : l'orientation, c'est du bonus.

(tu peux argumenter que notre but est de lutter contre le non recours, et que dans ce cas, c'est le simulateur qui est le bonus, le but c'est que l'usager fasse des démarches, je fais les questions et les réponses cet après midi)

Dans l'optique de réduire les clics parce qu'un clic c'est compliqué, je partirais plutôt sur une seule action : un truc comme "Entrez votre code postal pour connaitre les services près de chez vous" directement sur la page d'accueil, 5 chiffres, clic, paf, j'arrive sur une page avec tous les services autour de moi. Et par tous, en plus des CCAS / MSAP / départements, je rajoute les guichets CAF / Ameli / Pole Emploi... Afin de mieux orienter les personnes qui sont déjà un peu mieux informées ou en meilleure autonomie et qui savent à qui s'adresser (elles ont juste besoin d'un contact réel parce que le virtuel c'est pas leur truc).

**Comment by guillett** [comment]
Ce n'est pas une bonne stratégie ni un besoin exprimé directement pas un usager. Je ferme.
