### ISSUE TITLE
Données segmentées /stats : régions, départements

### ISSUE THREAD

**Issue by monbocal** [betagouv/mes-aides-ui#828]
Ajouter des données segmentées par régions et / ou départements sur la page /stats, afin de pouvoir approcher mieux les professionnels.

**Comment by guillett** [comment]
Il faut ajuster par la population.

**Comment by guillett** [comment]
Je ne pense pas qu'il y ait un besoin sur `/stats`.

La requête suivante fait le taff quand c'est nécessaire

``js

db.getCollection('situations').mapReduce(function() {
    if(this.menage && this.menage.depcom) {
        emit(this.dateDeValeur.toISOString().slice(0,7) + ";" + this.menage.depcom.slice(0,2),1);
    }
}, function(k,v) {
    return Array.sum(v);
}, {
    query: {
        dateDeValeur: {
            $gt: ISODate('2018-01-01'),
        },
        //'menage.depcom': /^13055/,
        modifiedFrom: { $exists: false },
    },
    out: { inline: 1 },
}).results.map(function(o) {
    return o._id + ";" + o.value;
}).join('\n')
``.
