### ISSUE TITLE
Restriction de push sur master aussi pour les admins

### ISSUE THREAD

**Issue by jdauphant** [betagouv/mes-aides-ui#831]
ça serait plus sécurisant de restreindre le push sur master pour les administrateurs (j'ai du faire bien attention pour faire ma PR mais loi de murphy dit que si c'est possible ça va se produire)

**Comment by guillett** [comment]
Merci beaucoup @jdauphant,

J'ai fait de modifications dans les paramètres GitHub.

Pourrais-tu me confirmer que tu ne peux plus simplement merger. Merci.

**Comment by jdauphant** [comment]
@guillett c'est bon ! (les merge ou l'edit directe de fichier sont bloqué)
