### ISSUE TITLE
Personnaliser le lien de sortie pour l'APA au Calvados

### ISSUE THREAD

**Issue by guillett** [betagouv/mes-aides-ui#853]
Le Calvados a mis en place un téléservice pour l'APA
https://teleservices.calvados.fr/

- [ ] Ajouter [une catégorie pour le Calvados](https://github.com/betagouv/mes-aides-ui/blob/master/app/js/services/customizationService.js#L8-L13) ;
- [ ] Ajouter [les données spécifiques](https://github.com/betagouv/mes-aides-ui/blob/master/app/js/constants/droits.js#L313-L337) au Calvados.

**Comment by guillett** [comment]
Peut-être intéressant : https://www.calvados.fr/contents/fiche/fiches-aide--services/lapa-en-ligne.html

**Comment by monbocal** [comment]
Je prends

**Comment by guillett** [comment]
Done ! Thanks @monbocal
