### ISSUE TITLE
Analyser les résultats de l'AB testing sur la page de résultats

### ISSUE THREAD

**Issue by guillett** [betagouv/mes-aides-ui#866]

**Comment by monbocal** [comment]
En comparant la valeur A et la valeur B à la variable link, ça donne...

Juillet 2018
```
AB-link-A
Visites : 179 883
Action Infos : 3875
Liens sortants vers service-public : 4523
```
```
AB-link-B
Visites : 179 365
Action Infos : 3843
Liens sortants vers service-public : 4434
```
Deux explications possibles :
- j'ai mal regardé les données
- ce test n'a montré aucun impact dans un sens ou dans l'autre, recommandation : abandon.

Ton avis @guillett  ?

**Comment by alexsegura** [comment]
Peut-on fermer cette issue ?

**Comment by guillett** [comment]
Il faut statuer et supprimer l'AB testing dans le code.
