### ISSUE TITLE
Générer les bonnes valeurs des champs du téléservice pour l'APA dans le Loiret

### ISSUE THREAD

**Issue by guillett** [betagouv/mes-aides-ui#870]
Les champs à construire et leur source ont été explicités dans le document communiqué par email.
En voilà l'extrait pertinent :
![capture d ecran de 2018-07-11 09-52-51](https://user-images.githubusercontent.com/1410356/42557987-3b2b051c-84f0-11e8-97a1-1f213c89508e.png)

Je pense que :
- pour les montants, les valeurs attendues sont les sommes sur les 12 derniers mois ;
- pour les dates, le format est le format français DD/MM/YYYY et
- pour les champs d'énumération (par exemple statut marital, il faut regarder plus en détail leur téléservice)

Extrait de _annexes/input/tpl_add/pub/demandeAPA.html_ :
```
<p><label for="situationfam_dem"> Situation<span class="etoile">*</span> :</label>
<select name="situationfam_dem" id="situationfam_dem" class="form_info_base" required>
  <option value="0"> Célibataire</option>
  <option value="4"> Concubinage</option>
  <option value="1"> Marié(e)</option>
  <option value="5"> Pacsé(e)</option>
  <option value="2"> Divorcé(e)</option>
  <option value="3"> Veuf(ve)</option>
</select></p> 
```

**Comment by alexsegura** [comment]
Ci-dessous les noms des champs pour le télé-service : 

<img width="662" alt="capture d ecran 2018-07-18 a 12 19 08" src="https://user-images.githubusercontent.com/1162230/42875728-d2ce5240-8a84-11e8-9b9e-ba8c1090b148.png">
