### ISSUE TITLE
Remove bluebird ?

### ISSUE THREAD

**Issue by alexsegura** [betagouv/mes-aides-ui#888]
There is a problem when running a fresh install of Mes Aides. 

```
TypeError: model.create(...).then(...).end is not a function
    at /srv/app/node_modules/ludwig-api/fixtures/index.js:31:16
    at Query.<anonymous> (/srv/app/node_modules/mongoose/lib/model.js:4081:16)
    at /srv/app/node_modules/kareem/index.js:273:21
    at /srv/app/node_modules/kareem/index.js:131:16
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

It can be fixed by commenting the [following line](https://github.com/betagouv/mes-aides-ui/blob/dc4aea26c6875ade9b34287ff8bbf9ecb2dfa42b/backend/config/mongoose.js#L6) in `backend/config/mongoose.js`

```diff
var path = require('path');
var fs = require('fs');

module.exports = function(mongoose, config) {

-    mongoose.Promise = require('bluebird');

    mongoose.connect(config.mongo.uri, config.mongo.options);

    // Bootstrap models
    var modelsPath = path.join(__dirname, '../models');
    fs.readdirSync(modelsPath).forEach(function (file) {
        if (/(.*)\.(js$|coffee$)/.test(file)) {
            require(modelsPath + '/' + file);
        }
    });

};
```

- Is there any significant benefit in using bluebird? 
- Is this mandatory with Mongoose?

From what I see, we are just using the `promisifyAll` utility.

**Comment by guillett** [comment]
Mongoose require a promise library. Maybe It was possible to do `mongoose.Promise = Promise`.

Plus `promisifyAll` is a good utility function.

The issue with `ludwig` was fixed. I think Bluebird can be kept. I close this issue.
