### ISSUE TITLE
Ajouter les liens APA pour le département du Nord

### ISSUE THREAD

**Issue by guillett** [betagouv/mes-aides-ui#898]
En lien avec #894 

- [ ] Trouver les liens pertinents : infos et action
- [ ] Trouver logo rattaché 
- [ ] Déterminer critères d'affichage
- [ ] Intégrer les 3 au dépôt 

Endroits _intéressants_
- https://github.com/betagouv/mes-aides-ui/blob/master/app/js/constants/droits.js
- https://github.com/betagouv/mes-aides-ui/blob/master/app/js/services/customizationService.js

**Comment by charlottelecuit** [comment]
Liens :
- informations : https://lenord.fr/jcms/prd2_335926/allocation-personnalisee-d-autonomie-apa
- call to action : https://lenord.fr/upload/docs/application/pdf/2018-04/formulaire_apa_2018-04-27_16-30-55_949.pdf

**Comment by charlottelecuit** [comment]
**Déterminer les critères d'affichage :** 
Afficher ces liens pour toutes les entrées relatives au département Nord (il ne semble pas qu'il y ait d'exception, puisque tous les sites des grandes villes redirigent les utilisateurs vers le site du département.) 

**Autres ressources qui peuvent être intéressantes, par grande ville :** 
- Lille : http://lillemetropole.point-infofamille59.fr/spip.php?article568
- Roubaix : http://www.ville-roubaix.fr/moments-de-vie/jai-plus-de-60-ans/les-aides-financieres.html
- Valenciennes : N/A
- Maubeuge : N/A
- Dunkerque : http://dunkerque.point-infofamille59.fr/spip.php?article568

**Pour toute la région, lien direct vers un annuaire géolocalisé, qui peut rediriger les utilisateurs vers des aides locales :** https://lenord.fr/jcms/dnw_137281/annuaire-geolocalise

**Comment by charlottelecuit** [comment]
Est-ce que c'est ça à peu près @guillett ? 

```
customization: {
                            'D59-NORD': {
                                provider: {
                                    imgSrc: 'https://dwpt1kkww6vki.cloudfront.net/img/logo/logo-departement-nord.png',
                                },
                                instructions: 'https://lenord.fr/upload/docs/application/pdf/2018-04/formulaire_apa_2018-04-27_16-30-55_949.pdf',
                                link: 'https://lenord.fr/jcms/prd2_335926/allocation-personnalisee-d-autonomie-apa',
                            },
```

**Comment by guillett** [comment]
Oui carrément !! Il faudra tout de même ajouter le logo dans le dépôt plutôt que faire référence à un fichier sur le net.

**Comment by guillett** [comment]
Fixed by #899
