### ISSUE TITLE
Mieux inciter à remplir les revenus n-2

### ISSUE THREAD

**Issue by monbocal** [betagouv/mes-aides-ui#916]
Je rencontre des simulations où les revenus n-2 n'ont pas été renseignés, sauf pour mettre un 0 dans une case sans rapport avec la situation de la personne. En cause : la formulation "Vous avez déclaré XXX pour les 12 derniers mois" qui peut mettre le doute : si le résultat est déjà noté, alors pourquoi est ce que je dois le rentrer à nouveau ?

**Comment by alexsegura** [comment]
Je suis plutôt d'accord. 
Ci-dessous un petit support visuel pour mieux comprendre le contexte. 

Est-ce qu'on peut imaginer de préremplir le champ, et de mettre un message du style 
> Nous avons pré rempli vos ressources (année N - 2) en fonction des ressources déclarées en (année N). Est-ce correct ?

<img width="707" alt="capture d ecran 2018-09-12 a 17 21 35" src="https://user-images.githubusercontent.com/1162230/45435201-5c124280-b6b0-11e8-9797-032ef2427420.png">

**Comment by monbocal** [comment]
Préremplir je pense que c'est trop next step. Mais une action "Utiliser mes revenus actuels comme revenus n-2" ça pourrait le faire oui !

**Comment by charlottelecuit** [comment]
je vois qu'une issue a déjà été créée sur ce sujet, je rajoute donc un point : quand j'appuie sur "entrer" après avoir rempli une case, il ne me met pas mon curseur à la case suivante, mais valide la page en entier. si ce n'est pas juste mon ordi, c'est possible de modifier ça pour faciliter le remplissage des champs ?

**Comment by guillett** [comment]
L'incitation à la saisie des revenus fiscaux a été revue dans la nouvelle version, en expliquant sur une page dédiée que si le montant qui est affiché n'est que celui attendu c'est peut-être à cause de notre mauvaise estimation de ces revenus là. (cf «montant inattendu ? » sur la page de résultat).

Sur la page de saisie, cet issue duplique #167. Je ferme donc pour n'avoir q'une seule issue.
