### ISSUE TITLE
Problèmes à l'installation

### ISSUE THREAD

**Issue by StephaneColson** [betagouv/mes-aides-ui#924]
Bonjour,

Je rencontre plusieurs soucis ne m'ayant pas permis de finaliser l'installation en suivant la documentation du Readme.
Environnement: MacBook Pro (MacOS 10.13.6)

### Version de Node
Tout d'abord, il est préconisé d'utiliser `Node v0.10`, mais dans ce cas, j'obtiens l'erreur suivante lors du `npm install`:

```
 /Users/stephane/github/mes-aides-ui/node_modules/string-width/index.js:2
 const stripAnsi = require('strip-ansi');
 ^^^^^
 SyntaxError: Use of const in strict mode.
     at Module._compile (module.js:439:25)
     at Object.Module._extensions..js (module.js:474:10)
     at Module.load (module.js:356:32)
     at Function.Module._load (module.js:312:12)
     at Module.require (module.js:364:17)
     at require (module.js:380:17)
     at Object.<anonymous> (/Users/stephane/github/mes-aides-ui/node_modules/wide-align/align.js:2:19)
     at Module._compile (module.js:456:26)
     at Object.Module._extensions..js (module.js:474:10)
     at Module.load (module.js:356:32)
```

`npm install` finit par contre correctement en utilisant `Node 4.9.1` (et pas avec `Node 10`). 
=> **La documentation est-elle bien à jour en préconisant `Node v0.10`?**

### Page de documentation sur virtualEnv
Ensuite je lis un lien vers `https://doc.openfisca.fr/for_developers.html#create-a-virtualenv` qui fait apparaitre une erreur de certificat invalide.

<img width="495" alt="screenshot at sep 25 11-24-31" src="https://user-images.githubusercontent.com/1481595/46012415-75ac8480-c0c9-11e8-9c1d-611f0a789e70.png">

En prenant le "risque" de charger la page, on est redirigé vers la page `https://fr.openfisca.org/api/v18/for_developers.html#create-a-virtualenv` qui elle n'existe pas du tout.
=> **Cela semble être une erreur dans la documentation, n'est-ce pas ?**

### Incompatibilités OpenFisca-France
Ensuite en faisant `$ npm run install-openfisca`, j'ai les avertissements suivant concernant des incompatibilités:

```
 Successfully built openfisca-France openfisca-BacASable openfisca-paris openfisca-BrestMetropole openfisca-RennesMetropole dpath PyYAML future psutil itsdangerous MarkupSafe
 openfisca-bacasable 0.0.3 has requirement OpenFisca-France<22,>=20.7, but you'll have openfisca-france 30.0.0 which is incompatible.
 openfisca-rennesmetropole 2.0.0 has requirement OpenFisca-France<22,>=20.7, but you'll have openfisca-france 30.0.0 which is incompatible.
 openfisca-brestmetropole 0.0.3 has requirement OpenFisca-France<22,>=20.7, but you'll have openfisca-france 30.0.0 which is incompatible.
```
Par la suite `openfisca` semble se lancer sans problème. Pareil pour `mongoDB`...

### Erreur du `npm start`
Lors du `npm start`

```
 2018-09-25T11:41:23.968+0200 I COMMAND  [conn4] mr failed, removing collectionNamespaceNotFound: namespace does not exist: dds.situations
 error { [MongoError: namespace does not exist: dds.situations]
   name: 'MongoError',
   message: 'namespace does not exist: dds.situations',
   ok: 0,
   errmsg: 'namespace does not exist: dds.situations',
   code: 26,
   codeName: 'NamespaceNotFound' }
 2018-09-25T11:41:23.993+0200 I NETWORK  [conn2] end connection 127.0.0.1:49364 (4 connections now open)
 2018-09-25T11:41:23.993+0200 I NETWORK  [conn3] end connection 127.0.0.1:49365 (3 connections now open)
 2018-09-25T11:41:23.994+0200 I NETWORK  [conn4] end connection 127.0.0.1:49366 (2 connections now open)
 2018-09-25T11:41:23.994+0200 I NETWORK  [conn5] end connection 127.0.0.1:49367 (1 connection now open)
 2018-09-25T11:41:23.994+0200 I NETWORK  [conn6] end connection 127.0.0.1:49368 (0 connections now open)
 
 npm ERR! Darwin 17.7.0
 npm ERR! argv "/Users/stephane/.nvm/versions/node/v4.9.1/bin/node" "/Users/stephane/.nvm/versions/node/v4.9.1/bin/npm" "run" "stats"
 npm ERR! node v4.9.1
 npm ERR! npm  v2.15.11
 npm ERR! code ELIFECYCLE
 npm ERR! sgmap-mes-aides-ui@12.1.3 stats: `node backend/lib/stats`
 npm ERR! Exit status 1
 npm ERR! 
 npm ERR! Failed at the sgmap-mes-aides-ui@12.1.3 stats script 'node backend/lib/stats'.
 npm ERR! This is most likely a problem with the sgmap-mes-aides-ui package,
 npm ERR! not with npm itself.
 npm ERR! Tell the author that this fails on your system:
 npm ERR!     node backend/lib/stats
 npm ERR! You can get information on how to open an issue for this project with:
 npm ERR!     npm bugs sgmap-mes-aides-ui
 npm ERR! Or if that isn't available, you can get their info via:
 npm ERR! 
 npm ERR!     npm owner ls sgmap-mes-aides-ui
 npm ERR! There is likely additional logging output above.
 
 npm ERR! Please include the following file with any support request:
 npm ERR!     /Users/stephane/github/mes-aides-ui/npm-debug.log
...
```

Voici les logs:

[npm-debug.log](https://github.com/betagouv/mes-aides-ui/files/2415079/npm-debug.log)

=> **Quel est le problème ici ? Manque une collection dans MongoDB ?**

### Tests unitaires en erreur
Enfin 3 tests unitaires échouent sur ma machine:

```
   1) Loiret Teleservice returns expected values for internal purpose:
      Error: Expected [ { label: 'votre date de naissance', formattedValue: '6 juin 1983' }, { label: 'votre situation familiale', formattedValue: 'En union libre' }, { label: 'vos salaires (net) sur les 12 derniers mois', formattedValue: '27 400,00 €' }, { label: 'votre retraite (net) sur les 12 derniers mois', formattedValue: '1 200,00 €' }, { label: 'vos allocations sur les 12 derniers mois', formattedValue: '2 400,00 €' }, { label: 'vos pensions alimentaires perçues', formattedValue: '0,00 €' }, { label: 'vos revenus locatifs', formattedValue: '0,00 €' }, { label: 'vos revenus du capital', formattedValue: '0,00 €' } ] to include { label: 'votre date de naissance', formattedValue: '5 juin 1983' }
       at assert (node_modules/expect/lib/assert.js:29:9)
       at Expectation.toInclude (node_modules/expect/lib/Expectation.js:215:28)
       at Context.<anonymous> (test/backend/teleservices/loiret.js:86:27)
 
   2) Loiret Teleservice returns expected values for date de naissance:
 
       Error: Expected '06/06/1983' to equal '05/06/1983'
       + expected - actual
 
       -06/06/1983
       +05/06/1983
       
       at assert (node_modules/expect/lib/assert.js:29:9)
       at Expectation.toEqual (node_modules/expect/lib/Expectation.js:81:30)
       at Context.<anonymous> (test/backend/teleservices/loiret.js:100:46)
 
   3) Loiret Teleservice returns expected values for date de naissance:
 
       Error: Expected '06/06/1983' to equal '05/06/1983'
       + expected - actual
 
       -06/06/1983
       +05/06/1983
       
       at assert (node_modules/expect/lib/assert.js:29:9)
       at Expectation.toEqual (node_modules/expect/lib/Expectation.js:81:30)
       at Context.<anonymous> (test/backend/teleservices/loiret.js:139:46)
```

Merci de votre aide. Je peux créer des Issues séparées sur demande, et vous donner plus d'informations si nécessaire.

**Comment by alexsegura** [comment]
Bonjour @StephaneColson 

Merci beaucoup de vous intéresser à Mes Aides 🙂

Vraiment désolé, le `README` n'est pas à jour, la version de Node à utiliser est `6.14.1`. 
Je vais corriger cela. 

Si vous voulez démarrer plus rapidement, nous fournissons également depuis peu [un environnement Docker](https://github.com/betagouv/mes-aides-ui/blob/c43f4f11bc0be9d00608c2a2e0f6bf71cdb7b6f0/DOCKER.md). 

> Erreur du npm start

Bizarre. Avez-vous bien créé la base de données via `npm run db` ?

> Tests unitaires en erreur

Ok, j'ai l'impression que c'est un problème d'horloge. Quelle est la date de votre système ?

**Comment by StephaneColson** [comment]
Merci @alexsegura pour la réponse. C'est sur qu'avec un `docker-compose` ça sera bien plus facile. Je vais essayer :)
 
> > Erreur du npm start
> 
> Bizarre. Avez-vous bien créé la base de données via `npm run db` ?

Oui, je vais réessayer avec la bonne version de `Node`

> 
> > Tests unitaires en erreur
> 
> Ok, j'ai l'impression que c'est un problème d'horloge. Quelle est la date de votre système ?

```
$ date
Tue Sep 25 15:01:36 CEST 2018
```

**Comment by alexsegura** [comment]
Je veux bien des retours sur l'utilisation de Docker 🙂
Je pense que vous rencontrerez quand même #888, je vais voir si je peux régler ça rapidement. 

Pour le test qui échoue, je regarde ça.

**Comment by StephaneColson** [comment]
En effet j'ai eu l'issue #888, en mettant en commentaire, j'ai une installation fonctionnelle.

**Comment by alexsegura** [comment]
Super ! Avec Docker donc ? 

Je suis vraiment désolé, on a pas beaucoup de contributeurs « externes », donc on a laissé traîner quelques issues de ce genre qui ne se produisent que sur une installation fraîche.

**Comment by StephaneColson** [comment]
Avec Docker oui. Un produit sans issues ne serait pas drôle :)

**Comment by alexsegura** [comment]
Du coup, si je peux me permettre, qu'est-ce que vous faîtes dans le coin ? 😃

Si vous souhaitez contribuer, la liste des Issues n'est peut-être pas très compréhensible, on peut essayer d'améliorer ça avec des _good first issues_
Mes Aides est un projet avec un trafic important, en production depuis pas mal de temps, donc c'est parfois « touchy » de faire certains changements. 

---

Je vois que vous êtres spécialisé dans les tests ? 
À ce propos, la machine Docker n'est pas 100% fonctionnelle pour lancer les tests Selenium et PhantomJS. Je suis disponible pour toute question. 

Vous pouvez à tout moment nous contacter directement sur contact@mes-aides.gouv.fr
Si vous êtes de passage à Paris, n'hésitez pas à nous faire signe !

**Comment by guillett** [comment]
Merci beaucoup @StephaneColson pour avoir pris le temps de créer cet issue. Merci @alexsegura d'avoir régler une bonne partie des problèmes. J'ai créé #963 et #964 pour séparer les sujets encore ouverts. @StephaneColson si le reste des problèmes identifiés te semble résolu, n'hésite pas à fermer l'issue.

**Comment by guillett** [comment]
Encore merci. Je ferme l'issue vu que les différents problèmes ont été soit résolus soit expliciter dans un autre issue.
