### ISSUE TITLE
Problème d'éditeur de date de naissance

### ISSUE THREAD

**Issue by StephaneColson** [betagouv/mes-aides-ui#928]
Sur la première page, saisir une date de naissance, par exemple 12/01/1980
Tenter de modifier cette date (on veut mettre 12/02/1980 à la place), avec le curseur et les flèches clavier ou avec la souris en se mettant après le '12/01' puis faire Suppression arrière.

**Attendu**: Le '1' est supprimé, on se retrouve avec 12/0/1980 et on peut saisir 2 pour avoir 12/02/1985. D'une manière générale, on devrait pouvoir utiliser son clavier normalement pour saisir une date.
**Observé**: Le '1' n'est pas supprimé, on se retrouve avec 12/01/980. Si je fais encore suppression arrière, j'ai maintenant 12/09/80

A priori c'est un composant Custom qui est utilisé. On veut que la personne ait plus de 18 ans, qu'elle soit déjà née, qu'elle ait moins de 130 ans et que la date soit valide (pas un 31 février par exemple). Peut-être y a-t-il d'autres critères que je n'ai pas vu.

Un gif animé valant mieux qu'un discours:
![saisiedatedenaissance](https://user-images.githubusercontent.com/1481595/46147392-b04b2400-c265-11e8-9abf-f70c62751cc0.gif)

**Comment by monbocal** [comment]
En lien avec #813, #343 et #494 . Je passe la main à @alexsegura qui pourra peut-être trouver une solution élégante :)

**Comment by alexsegura** [comment]
Alors on utilise effectivement une [directive Angular.js](https://github.com/betagouv/mes-aides-ui/blob/9827270a190e3932104b172495603f88aeb1183b/app/js/directives/date.js) qui est basée sur [Cleave.js](https://nosir.github.io/cleave.js/). 

La version de Cleave.js qu'on utilise est assez vieille, mais même en utilisant la dernière version, le problème persiste. Il y a une Issue pour ce problème nosir/cleave.js#420

Honnêtement je pense qu'on peut passer à l'usage de [`<input type="date">`](https://developer.mozilla.org/fr/docs/Web/HTML/Element/Input/date), le support est plutôt [très bon](https://caniuse.com/#feat=input-datetime). Plus de 2 ans ont passé depuis #343. Le seul "problème" reste que l'apparence est toujours inconsistante entre les navigateurs, mais je ne trouve pas que c'est bloquant. 

Ça permettrait de supprimer la dépendance Cleave.js + simplifier voire supprimer la directive Angular.js + avoir un sélecteur de dates beaucoup plus pratique sur les smartphones (c'est à dire une grosse partie de notre trafic). Bref, ça paye de la dette. 

Je vais faire des essais en ce sens.
