### ISSUE TITLE
Hiérarchiser l'ordre d'affichage des aides en fin de parcours

### ISSUE THREAD

**Issue by charlottelecuit** [betagouv/mes-aides-ui#930]
**D'après la situation que vous avez décrite, vous êtes a priori éligible à ces aides nationales. Les montants avancés sont arrondis à une dizaine d'euros près :**
**Dans un premier encadré :** 
-> En 1er : les aides dont le montant est le plus sûr 
-> En 2e : CMU-C ou autres aides dont il n'y a pas de montant affiché

**Voici les aides que vous touchez peut-être, en fonction de vos ressources de l'année 2016.**
Pour le moment, nous avons supposé que vos ressources pour l’année 2016 étaient les mêmes qu’entre octobre 2017 et septembre 2018 : _message à mettre dans un (i) à la fin de la phrase d'avant ?_ [Bouton 'Déclarer mes ressources 2016']
**Dans un 2e encadré :**
-> Liste de ces aides
_Je propose de garder le grisé pour qu'on voit quand même que ça dépend des ressources, mais d'enlever le point d'exclamation jaune du coup._

**Comment by guillett** [comment]
Je ferme suite à la refonte de la page de résultats. Les messages sont plus clairs.
