### ISSUE TITLE
Attempting to use an unsafe value in a safe context

### ISSUE THREAD

**Issue by alexsegura** [betagouv/mes-aides-ui#946]
- Faire une simulation, et récupérer l'identifiant
- Aller sur `https://mes-aides.gouv.fr/recap-situation/<identifiant>`

<img width="792" alt="capture d ecran 2018-10-30 a 14 02 52" src="https://user-images.githubusercontent.com/1162230/47719837-a80f4b80-dc4c-11e8-8777-98d3bde02334.png">

**Comment by guillett** [comment]
Broken differently with #954.
Fixed by #1007.
