### ISSUE TITLE
Neutraliser les revenus professionnels substitués

### ISSUE THREAD

**Issue by fpagnoux** [betagouv/mes-aides-ui#95]
Les revenus professionnels interrompus mais substitués ne devraient pas être neutralisés dans le calcul du RSA. 

[Test](https://mes-aides.gouv.fr/tests/5571c3f30efa6d80143ea331/show)

Depends on #22

**Comment by HelaG** [comment]
Confirmé par la DGCS:
Les revenus de substitution sont essentiellement les IJ, la retraite ou le chômage.

**Comment by MattiSG** [comment]
@fpagnoux Hasn't this been fixed?

**Comment by guillett** [comment]
Le test n'avait pas de revenus de substitution, je l'ai modifié et la neutralisation n'es plus faite. Je ferme cet issue.


Pour référence, l'identifiant de la situation était `5571c3eb78ebb479142d52ee`, c'est désormais `5bf7e599b603ef21643840c7`.
