### ISSUE TITLE
Nouvel outil de test des règles d'éligibilité

### ISSUE THREAD

**Issue by charlottelecuit** [betagouv/mes-aides-ui#958]
- Super que ce soit déjà une page intégrée à mes-aides, ça donne plus de fluidité! 😊 
- Je trouve le _'Valeurs attendues'_ peu visible, et il pourrait peut-être y avoir déjà les cases des aides par défaut comme sur Ludwig, sinon ça incite à ne remplir que les cases _'Nom du test'_ et _'Description'._
- Le wording _'Valeurs attendues'_ n'est pas forcément clair quand on ne voit pas les deux cases avec l'intitulé de l'aide et un montant associé. Peut-être qu'il faudrait quelque chose de plus explicite, du type de 'montants de prestations qui vous semblent erronés', ou qqch comme ça?
- Sur la partie _'Détails de la situation'_, pas sur qu'on comprenne la variable "bic" (ex: tns_autres_revenus_type_activite: bic). 
- Lorsqu'on clique sur '_Aide au logement'_ parmi les valeurs attendues, je ne comprends pas trop l'enchainement 'la valeur doit elle etre calculable', puis 'quelle est la raison?'

**Comment by guillett** [comment]
Merci @charlottelecuit pour ce test.

1. Cool
2. Si des prestations sont affichées par défaut, les personnes ne les suppriment pas alors qu'elles ne savent pas quelles sont les valeurs attendues.
3. L'objectif n'est pas que de _corriger_ le simulateur mais c'est aussi de confirmer des résultats déjà corrects. Que penses-tu de :
    - _Montants des prestations pour lesquelles vous connaissez la valeur attendue_
    - _Montants des prestations que vous connaissez_
    - _Prestations dont vous connaissez les valeurs attendues_
    - _Prestations dont vous connaissez les valeurs exactes_
4. Mmhh, Je suis d'accord avec toi. Pour info, ce sont les valeurs par défaut de certains champs. Il faudrait voir si on pourrait être plus malin à moindre frais.
5. As-tu regarder les _raisons_ possible de non _calculabilité_ ? Certaines aides ne sont pas calculables par OpenFisca (pour le moment ?) donc c'est une façon d'indiquer cela aux personnes qui créé des tests. Je suis d'accord avec toi ce n'est pas idéal.

**Comment by charlottelecuit** [comment]
2. Alors peut-être ne pas mettre de valeurs par défaut, mais de rendre ce champ plus visible? Je pense que si je ne savais pas comment fonctionne le test j'aurais peut-être zappé et mis toutes les infos dans la case Description. 
3. Ok ça marche. Alors _Prestations dont vous connaissez les valeurs attendues_ me semble pas mal en effet. 
5. Oui j'ai regardé, c'était pour l'aide au logement, mais peut-être que c'est plus simple si tu m'expliques ça de vive voix, parce que je ne vois pas pq ça indique qu'on n'arrive pas à le calculer pour le moment. c'est la partie 'quelle est la raison?' que je ne comprends pas. 
6. Aussi, du coup, pour le wording de ces questions, est-ce qu'on peut mettre 'la valeur est elle calculable?', c'est moins lourd je trouve.

**Comment by guillett** [comment]
Je propose comme discuté, de limiter les changements à ce qui va être affiché à la plupart des utilisateurs de cette vue (la question Cette variable est-elle calculable est rarement pertinente, en cas de problème dans le futur on fera les modificatoins nécessaires).
