### ISSUE TITLE
[UX] Améliorer l'affichage des points d'accueil physique

### ISSUE THREAD

**Issue by charlottelecuit** [betagouv/mes-aides-ui#968]
- [ ] Créer deux blocs distincts avec des titres 1. pour les aides, 2. pour les points d'accueil physique pour que les utilisateurs identifient clairement les 2 informations principales de cette page. 
Propositions de titres: 
- Vous avez droit à ces aides + Vous avez besoin d'être accompagné? Rendez-vous dans ces lieux près de chez vous
- Aides auxquelles vous avez droit + Lieux près de chez vous/[nom ville associé à CP rentré] pour vous faire accompagner
- Aides que vous pouvez demander + Besoin de conseils ou d'informations? Rendez-vous dans ces lieux
- Vos aides + Vos lieux d'accueil et d'accompagnement

- [ ] Revoir wording et forme "D'après la situation que vous avez décrite, vous êtes a priori éligible à ces aides nationales. Les montants avancés sont arrondis à une dizaine d'euros près", 
=> 2 raisons: 1. pas besoin de distinguer national/local, 2. texte rarement lu.

**Comment by monbocal** [comment]
Cette séparation existe déjà : le bloc avec les aides d'une part, puis un bloc avec "Consulter la liste". Le problème viendrait alors que ce bloc est trop semblable aux autres actions du dessus (patrimoine, n-2).

On pourrait résoudre ça avec un titre entre les deux comme tu le suggère, à voir quel meilleur wording utiliser dans la globalité.

**Comment by charlottelecuit** [comment]
Oui mais la séparation n'existe que grâce aux blocs justement, qui sont peu visibles. Tu penses quoi @monbocal des différentes propositions de titres que j'ai faites?

**Comment by guillett** [comment]
J'ai renommé cette issue pour l'actualiser et la recentrer sur le nouveau besoin.

**Comment by ManonLger** [comment]
A déjà été résolu par :
https://github.com/betagouv/mes-aides-ui/pull/1328
https://github.com/betagouv/mes-aides-ui/pull/1266
