### ISSUE TITLE
[UX] Page de résultat - Aides grisés/Point d'interrogation/Panneau "attention"  

### ISSUE THREAD

**Issue by charlottelecuit** [betagouv/mes-aides-ui#969]
D'après plusieurs utilisateurs qui ont testé le site:
- la première chose qu'on voit en arrivant sur la dernière page, c'est la colonne avec les montants, les points d'interrogation, et les panneaux "Attention". Souvent, ils ne comprennent pas ce que signifient ces différents signes. 
- l'accumulation du panneau orange et du grisé rend les lignes concernées invisibles pour plusieurs utilisateurs qui ont fait le test: ils se disent que ce ne sont pas des aides auxquelles ils peuvent vraiment avoir droit. 

Le problème, c'est que ça leur donne **une impression générale de flou** quand ils arrivent sur cette page, et qu'ils ne sont **pas encouragés à poursuivre leurs démarches**. 

Je propose donc (évidemment, à voir ensemble):

- d'enlever le grisé,
- de remplacer le point d'interrogation par un court texte du type de "À confirmer", "À valider", qui ouvre le détail de l'aide lorsqu'on clique dessus, et qui permet à l'utilisateur de comprendre pourquoi il faut confirmer/valider que l'utilisateur a bien droit à cette aide,
- trouver un autre signifiant que le triangle orange, dont la légende est rarement lue: 
--- option1: remplacer le triangle orange par un court texte du type "Déclarez vos ressources pour confirmer", qqch comme ça.
--- option2: Avoir une page intermédiaire pour les personnes qui ont besoin de déclarer leurs ressources 2016 genre "un dernier petit effort, certaines aides dépendent de vos ressources de l'année 2016", etc.
--- option3: Intégrer déclaration ressources 2016 dans le parcours en amont.

**Comment by monbocal** [comment]
Je proposerai de faire des groupes d'aide dans ce cas. Actuellement les aides sont triées par ordre alphabétique. L'idée serait d'avoir :

- Aides que nous avons pu calculer a priori
-- les aides actuellement en blanc
- Aides potentielles
-- "Pour confirmer ces aides, vous devez également"
--- Remplir votre patrimoine
--- Remplir vos ressources 2016
-- Liste des aides actuellement en grisé

**Comment by guillett** [comment]
Superseeded by #1072. :)
