### ISSUE TITLE
[UX] Page de résultat - Couleurs des boutons

### ISSUE THREAD

**Issue by charlottelecuit** [betagouv/mes-aides-ui#970]
Dans une même page de résultat, on peut avoir jusqu'à 4 couleurs différentes de boutons, de plusieurs tailles: bleu ("accéder au formulaire"), vert ("faire une demande" d'aide, "déclarez vos ressources 2016"), gris sur fond blanc ("déclarer votre patrimoine", "consulter la liste"), gris sur fond gris ("télécharger ma simulation"). 

ça rend certaines informations quasi invisibles et brouille l'utilisateur sur d'autres infos. 
Plus précisément : 
- le bouton "consulter la liste" est rarement vu,
- les boutons "accéder au formulaire" et "faire une demande" pourraient être de la même couleur puisque le CTA est quasiment le même,
- il est confusant que le bouton "déclarer vos ressources" et "faire une demande" soient de la même couleur, alors que les CTA sont différents. 

Je propose donc:
- de mettre le bouton "consulter la liste" dans une couleur plus visible (vert?)
_en comptant que ce problème va probablement disparaître lorsque la section Points d'accueil physiques sera clairement identifiée_
- de mettre tous les CTA de demande d'aide de la même couleur (bleu?)
- que le bouton Déclarer vos ressources soit en orange, et plus visiblement lié au texte qui est à sa gauche (Nous avons supposé que vos ressources pour l’année 2016 étaient les mêmes qu’entre novembre 2017 et octobre 2018.) car apparemment les utilisateurs ne voient pas le lien entre les 2.

**Comment by monbocal** [comment]
Avoir des couleurs liées aux symboles est effectivement important - ainsi qu'une charte des couleurs qui soit logique pour l'utilisateur. A voir cependant une fois que #968 et #969 seront résolus - on risque d'itérer sur quelque chose qui sera peut-être obsolète.
