### ISSUE TITLE
[RFR] Ajouter les revenus fonciers n-2

### ISSUE THREAD

**Issue by monbocal** [betagouv/mes-aides-ui#987]
Bonjour,

Notre calcul du RFR ne prends pas en compte les revenus fonciers possibles en n-2, même si OpenFisca le gère.

Il faudrait permettre de déclarer ses revenus fonciers en n-2 afin d'avoir une meilleure estimation, notamment pour les aides qui en dépendent comme le chèque énergie.

Cordialement,

**Comment by guillett** [comment]
Linked to #1096.
