### ISSUE TITLE
Préciser "Avant retenue à la source"

### ISSUE THREAD

**Issue by monbocal** [betagouv/mes-aides-ui#993]
Sur la page de déclaration des salaires etc., précisez "Entrez le montant avant la retenue à la source".

Afin d'éviter les mails dès le 2 janvier sur ce sujet.

**Comment by alexsegura** [comment]
@monbocal j'ai fait comme ça, qu'en penses-tu ?

<img width="855" alt="capture d ecran 2018-12-19 a 12 15 02" src="https://user-images.githubusercontent.com/1162230/50217115-1ab4c180-0388-11e9-87bc-c8e08feb4e5d.png">

**Comment by guillett** [comment]
Sur quelles ressources cela est-il ajouté ?
Est-ce accessible ?
Je suis plutôt _brute force_ genre ajouter aux _bonnes_ ressources la mention _avant la retenue à la source_.

**Comment by alexsegura** [comment]
@guillett c'est ajouté aux ressources qui ont une clé `hint`

Voir #998
